id: Generic-Soil
brand: Generic
model: Soil Moisture Sensor Module
url: https://www.arduinoall.com/product/1836/soil-moisture-sensor-v2-for-arduino-red-pcb-keys
type: MODULE
width: 124
height: 320
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: GND
    type: WIRE
    pins:
    - x: 48
      y: 319
      pin_function: GND
  - name: VCC
    type: WIRE
    pins:
    - x: 62.4
      y: 319
      pin_function: VCC
  - name: SIG
    type: WIRE
    pins:
    - x: 76.8
      y: 319
      pin_function: ANALOG_OUT
compatibility:
- name: Soil Moisture
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SOIL_MOISTURE
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_SOIL_MOISTURE
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_SOIL_MOISTURE
  library_dependency: []
