id: Generic-DHT22
brand: Generic
model: DHT22 Digital Temperature and Humidity Sensor
url: https://www.arduinoall.com/product/825/dht22-am2302-module-%E0%B9%82%E0%B8%A1%E0%B8%94%E0%B8%B9%E0%B8%A5%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%AD%E0%B8%B8%E0%B8%93%E0%B8%AB%E0%B8%A0%E0%B8%B9%E0%B8%A1%E0%B8%B4%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%8A%E0%B8%B7%E0%B9%89%E0%B8%99-temperature-and-humidity-sensor-module-%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%AA%E0%B8%B2%E0%B8%A2%E0%B9%84%E0%B8%9F
type: MODULE
width: 77
height: 226
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: +
    type: WIRE
    pins:
    - x: 26.4
      y: 224
      pin_function: VCC
  - name: out
    type: WIRE
    pins:
    - x: 40.8
      y: 224
      pin_function: DIGITAL_OUT
  - name: '-'
    type: WIRE
    pins:
    - x: 55.2
      y: 224
      pin_function: GND
compatibility:
- name: Temperature
  condition:
  - name: Compare
  value:
  - name: Temperature
    constraint:
      min: -40
      max: 80
      unit: CELSIUS
- name: Humidity
  condition:
  - name: Compare
  value:
  - name: Humidity
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_DHT22
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.3.3
- platform: ARDUINO_ESP8266
  classname: MP_DHT22
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.3.3
- platform: ARDUINO_ESP32
  classname: MP_DHT22
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.3.3
- platform: ARDUINO_ATSAMD21
  classname: MP_DHT22
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.3.3
- platform: ARDUINO_ATSAMD51
  classname: MP_DHT22
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.3.3
- platform: RASPBERRYPI
  classname: MP_DHT22
  info_message:
  - 'The device required user to install an external library: "pip3 install Adafruit_DHT"'
  library_dependency: []
