id: Generic-HC-SR04P
brand: Generic
model: Ultrasonic Sensor Module HC-SR04P
url: "https://www.arduinoall.com/product/1533/ultrasonic-sensor-module-hc-sr04p-\u0E42\
  \u0E21\u0E14\u0E39\u0E25-ultrasonic-hc-sr04-p"
type: MODULE
width: 256
height: 132
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: VIN
    type: WIRE
    pins:
    - x: 105.6
      y: 132
      pin_function: VCC
  - name: TRIG
    type: WIRE
    pins:
    - x: 120
      y: 132
      pin_function: DIGITAL_IN
  - name: ECHO
    type: WIRE
    pins:
    - x: 134.4
      y: 132
      pin_function: DIGITAL_OUT
  - name: GND
    type: WIRE
    pins:
    - x: 148.8
      y: 132
      pin_function: GND
compatibility:
- name: Distance
  condition:
  - name: Compare
  value:
  - name: Distance
    constraint:
      min: 2
      max: 450
      unit: CENTIMETER
platforms:
- platform: ARDUINO_AVR8
  classname: MP_HC_SR04
  library_dependency:
  - teckel12/NewPing_v1.9.1
- platform: ARDUINO_ESP8266
  classname: MP_HC_SR04
  library_dependency:
  - teckel12/NewPing_v1.9.1
- platform: ARDUINO_ESP32
  classname: MP_HC_SR04
  library_dependency:
  - teckel12/NewPing_v1.9.1
- platform: ARDUINO_ATSAMD21
  classname: MP_HC_SR04
  library_dependency:
  - teckel12/NewPing_v1.9.1
- platform: ARDUINO_ATSAMD51
  classname: MP_HC_SR04
  library_dependency:
  - teckel12/NewPing_v1.9.1
- platform: ARDUINO_K210
  classname: MP_HC_SR04
  library_dependency:
    - teckel12/NewPing_v1.9.1
- platform: RASPBERRYPI
  classname: MP_HC_SR04
  library_dependency: []
