id: Generic-DHT11
brand: Generic
model: DHT11 Digital Temperature and Humidity Sensor
url: https://www.arduinoall.com/product/653/dht11-digital-temperature-and-humidity-sensor-dht11-%E0%B9%81%E0%B8%9A%E0%B8%9A-pcb-%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%AA%E0%B8%B2%E0%B8%A2%E0%B9%84%E0%B8%9F
type: MODULE
width: 68
height: 159
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: VIN
    type: WIRE
    pins:
    - x: 19.6
      y: 158
      pin_function: VCC
  - name: OUT
    type: WIRE
    pins:
    - x: 34
      y: 158
      pin_function: DIGITAL_OUT
  - name: GND
    type: WIRE
    pins:
    - x: 48.4
      y: 158
      pin_function: GND
compatibility:
- name: Temperature
  condition:
  - name: Compare
  value:
  - name: Temperature
    constraint:
      min: 0
      max: 50
      unit: CELSIUS
- name: Humidity
  condition:
  - name: Compare
  value:
  - name: Humidity
    constraint:
      min: 20
      max: 80
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_DHT11
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.4.0
- platform: ARDUINO_ESP8266
  classname: MP_DHT11
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.4.0
- platform: ARDUINO_ESP32
  classname: MP_DHT11
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.4.0
- platform: ARDUINO_ATSAMD21
  classname: MP_DHT11
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.4.0
- platform: ARDUINO_ATSAMD51
  classname: MP_DHT11
  library_dependency:
  - adafruit/Adafruit_Sensor-1.1.4
  - adafruit/DHT-sensor-library-1.4.0
