id: SeeedStudio-101020083
brand: SeeedStudio
model: Grove - Gesture Sensor
url: https://www.seeedstudio.com/Grove-Gesture-PAJ7620U2.html
type: MODULE
width: 169
height: 142
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 64
      y: 117
      pin_function: GND
    - x: 78.4
      y: 117
      pin_function: VCC
    - x: 92.8
      y: 117
      pin_function: SDA
    - x: 107.2
      y: 117
      pin_function: SCL
compatibility:
- name: Gesture
  condition:
  - name: Swipe Up
  - name: Swipe Down
  - name: Swipe Left
  - name: Swipe Right
  - name: Move Forward
  - name: Move Backward
  - name: Spin Clockwise
  - name: Spin Counter Clockwise
  - name: Waving
  - name: Not Detected
platforms:
- platform: ARDUINO_AVR8
  classname: MP_PAJ7620U2
  library_dependency:
  - SeeedStudio/Gesture_PAJ7620-1.0.0
- platform: ARDUINO_ESP8266
  classname: MP_PAJ7620U2
  library_dependency:
  - SeeedStudio/Gesture_PAJ7620-1.0.0
- platform: ARDUINO_ESP32
  classname: MP_PAJ7620U2
  library_dependency:
  - SeeedStudio/Gesture_PAJ7620-1.0.0
- platform: ARDUINO_ATSAMD21
  classname: MP_PAJ7620U2
  library_dependency:
  - SeeedStudio/Gesture_PAJ7620-1.0.0
- platform: ARDUINO_ATSAMD51
  classname: MP_PAJ7620U2
  library_dependency:
  - SeeedStudio/Gesture_PAJ7620-1.0.0
