id: M5Stack-Relay
brand: M5Stack
model: Relay
url: https://www.seeedstudio.com/Grove-Relay-p-769.html
type: MODULE
width: 138
height: 271
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 52.5
      y: 265.5
      pin_function: GND
    - x: 64
      y: 265.5
      pin_function: VCC
    - x: 75
      y: 265.5
      pin_function: DIGITAL_OUT
    - x: 86.5
      y: 265.5
      pin_function: NO_FUNCTION
compatibility:
- name: Relay Module
  action:
  - name: 'On'
    parameter: []
  - name: 'Off'
    parameter: []
  value: []
platforms:
- platform: ARDUINO_ESP32
  classname: MP_RELAY
  library_dependency: []
