id: Grove-105020012
brand: SeeedStudio
model: Grove 6-Axis Accelerometer&Gyroscope
url: https://www.seeedstudio.com/Grove-6-Axis-Accelerometer-Gyroscope-p-2606.html
type: MODULE
width: 166
height: 140
pin_template: GENERIC_I2C_DEVICE_3v3_5
connection_consume:
  - name: Port
    type: GROVE
    pins:
      - x: 103
        y: 24
        ref_to: GND
      - x: 88.6
        y: 24
        ref_to: VCC
      - x: 74.2
        y: 24
        ref_to: SDA
      - x: 59.8
        y: 24
        ref_to: SCL
compatibility:
  - name: Accelerometer
    condition:
      - name: Compare
    value:
      - name: Accel_X
        constraint:
          min: -100
          max: 100
          unit: METERPERSECSQUARE
      - name: Accel_Y
        constraint:
          min: -100
          max: 100
          unit: METERPERSECSQUARE
      - name: Accel_Z
        constraint:
          min: -100
          max: 100
          unit: METERPERSECSQUARE
      - name: Accel_Magnitude
        constraint:
          min: 0
          max: 100
          unit: METERPERSECSQUARE
  - name: Gyroscope
    condition:
      - name: Compare
    value:
      - name: Gyro_X
        constraint:
          min: -200
          max: 200
          unit: RADIUSPERSEC
      - name: Gyro_Y
        constraint:
          min: -200
          max: 200
          unit: RADIUSPERSEC
      - name: Gyro_Z
        constraint:
          min: -200
          max: 200
          unit: RADIUSPERSEC
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LSM6DS3
  library_dependency:
    - SeeedStudio/Accelerometer_And_Gyroscope_LSM6DS3-1.0.1
- platform: ARDUINO_ESP8266
  classname: MP_LSM6DS3
  library_dependency:
    - SeeedStudio/Accelerometer_And_Gyroscope_LSM6DS3-1.0.1
- platform: ARDUINO_ESP32
  classname: MP_LSM6DS3
  library_dependency:
    - SeeedStudio/Accelerometer_And_Gyroscope_LSM6DS3-1.0.1
- platform: ARDUINO_ATSAMD51
  classname: MP_LSM6DS3
  library_dependency:
    - SeeedStudio/Accelerometer_And_Gyroscope_LSM6DS3-1.0.1