id: MP-TinyBoard
brand: Maker Playground
model: TinyBoard
url: ''
type: CONTROLLER
pio_boardid: nodemcuv2
cloud_provide:
- cloud_platform: NETPIE
  classname: MP_NETPIE_ESP
  library_dependency:
  - netpieio/microgear-esp8266-arduino
- cloud_platform: BLYNK
  classname: MP_BLYNK_NODEMCU
  library_dependency:
  - makerplayground/blynk-library
width: 142
height: 238
pin_template: ESP_12
connection_provide:
  voltage_level: LEVEL_3v3
  items:
  - name: D1
    type: MAKER_PLAYGROUND
    pins:
    - x: 85
      y: 188
      ref_to: GND
    - x: 85
      y: 176
      ref_to: VCC
    - x: 85
      y: 164
      ref_to: IO14
    - x: 85
      y: 152
      ref_to: IO16
  - name: D2
    type: MAKER_PLAYGROUND
    pins:
    - x: 120
      y: 188
      ref_to: GND
    - x: 120
      y: 176
      ref_to: VCC
    - x: 120
      y: 164
      ref_to: IO12
    - x: 120
      y: 152
      ref_to: IO13
  - name: A1
    type: MAKER_PLAYGROUND
    pins:
    - x: 51
      y: 188
      ref_to: GND
    - x: 51
      y: 176
      ref_to: VCC
    - x: 51
      y: 164
      ref_to: NF
    - x: 51
      y: 152
      ref_to: ADC
      voltage_level: LEVEL_3v3
  - name: I2C/D3
    type: MAKER_PLAYGROUND
    pins:
    - x: 17
      y: 188
      ref_to: GND
    - x: 17
      y: 176
      ref_to: VCC
    - x: 17
      y: 164
      ref_to: IO4
    - x: 17
      y: 152
      ref_to: IO5
compatibility: []
platforms:
- platform: ARDUINO_ESP8266
  classname: ''
  library_dependency: []
