id: SeeedStudio-103020272
brand: SeeedStudio
model: Grove - I2C Hub (6 Port)
url: https://www.seeedstudio.com/Grove-I2C-Hub-6-Port-p-4349.html
type: MODULE
formfactor: STANDALONE
width: 331
height: 186
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port0
    type: GROVE
    pins:
    - x: 29
      y: 68
      pin_function: GND
    - x: 29
      y: 92.4
      pin_function: VCC
    - x: 29
      y: 106.8
      pin_function: SDA
    - x: 29
      y: 121.2
      pin_function: SCL
  - name: Port1
    type: GROVE
    pins:
    - x: 29
      y: 68
      pin_function: GND
    - x: 29
      y: 92.4
      pin_function: VCC
    - x: 29
      y: 106.8
      pin_function: SDA
    - x: 29
      y: 121.2
      pin_function: SCL
  - name: Port2
    type: GROVE
    pins:
    - x: 29
      y: 68
      pin_function: GND
    - x: 29
      y: 92.4
      pin_function: VCC
    - x: 29
      y: 106.8
      pin_function: SDA
    - x: 29
      y: 121.2
      pin_function: SCL
  - name: Port3
    type: GROVE
    pins:
    - x: 29
      y: 68
      pin_function: GND
    - x: 29
      y: 92.4
      pin_function: VCC
    - x: 29
      y: 106.8
      pin_function: SDA
    - x: 29
      y: 121.2
      pin_function: SCL
  - name: Port4
    type: GROVE
    pins:
    - x: 29
      y: 68
      pin_function: GND
    - x: 29
      y: 92.4
      pin_function: VCC
    - x: 29
      y: 106.8
      pin_function: SDA
    - x: 29
      y: 121.2
      pin_function: SCL
  - name: Port5
    type: GROVE
    pins:
    - x: 29
      y: 68
      pin_function: GND
    - x: 29
      y: 92.4
      pin_function: VCC
    - x: 29
      y: 106.8
      pin_function: SDA
    - x: 29
      y: 121.2
      pin_function: SCL
compatibility: []
platforms:
- platform: ARDUINO_AVR8
  classname: ''
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: ''
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: ''
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: ''
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: ''
  library_dependency: []
