id: MP-RGBLED
brand: Maker Playground
model: RGB LED
url: ''
type: MODULE
formfactor: MP_DEVICE
width: 124
height: 108
property: []
pin_template: MAKER_PLAYGROUND_RGB_LED
connection_consume:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
      - x: 79
        y: 110
        ref_to: GND
      - x: 68
        y: 110
        ref_to: VCC
      - x: 57
        y: 110
        ref_to: SIG2
      - x: 46
        y: 110
        ref_to: SIG1
compatibility:
- name: RGB LED
  action:
  - name: 'On'
    parameter:
    - name: Red
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Green
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Blue
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Brightness
      constraint:
        min: 0
        max: 100
        unit: NOT_SPECIFIED
  - name: 'Off'
    parameter: []
  value: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_RGB_LED
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_RGB_LED
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_RGB_LED
  library_dependency: []
