id: MP-RGBLED
brand: Maker Playground
model: RGB LED
url: ''
type: MODULE
formfactor: MP_DEVICE
width: 124
height: 108
property: []
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 79
      y: 110
      pin_function: GND
    - x: 68
      y: 110
      pin_function: VCC
    - x: 57
      y: 110
      pin_function: DIGITAL_IN
    - x: 46
      y: 110
      pin_function: DIGITAL_IN
compatibility:
- name: RGB LED
  action:
  - name: 'On'
    parameter:
    - name: Red
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Green
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Blue
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Brightness
      constraint:
        min: 0
        max: 100
        unit: NOT_SPECIFIED
  - name: 'Off'
    parameter: []
  value: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_RGB_LED
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_RGB_LED
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_RGB_LED
  library_dependency: []
