id: Generic-HC-SR501
brand: Generic
model: PIR Motion Sensor Module HC-SR501
url: https://www.arduinoall.com/product/29/motion-sensor-arduino-pir-hc-sr501-%E0%B9%80%E0%B8%8B%E0%B8%99%E0%B9%80%E0%B8%8B%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%95%E0%B8%A3%E0%B8%A7%E0%B8%88%E0%B8%88%E0%B8%B1%E0%B8%9A%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B9%80%E0%B8%84%E0%B8%A5%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%99%E0%B9%84%E0%B8%AB%E0%B8%A7-infrared-sensor-arduino-hc-sr501
type: MODULE
width: 235
height: 230
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: 5V
    type: WIRE
    pins:
    - x: 135.0
      y: 229.074
      pin_function: VCC
  - name: GND
    type: WIRE
    pins:
    - x: 99.0
      y: 229.074
      pin_function: GND
  - name: DO
    type: WIRE
    pins:
    - x: 117.0
      y: 229.074
      pin_function: DIGITAL_OUT
compatibility:
- name: Presence
  condition:
  - name: Detect Human
  - name: No Human
platforms:
- platform: ARDUINO_AVR8
  classname: MP_PIR
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_PIR
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_PIR
  library_dependency: []
