id: MP-LED
brand: Maker Playground
model: LED
url: ''
type: MODULE
width: 124
height: 108
property: []
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 46
      y: 100
      pin_function: GND
    - x: 57
      y: 100
      pin_function: VCC
    - x: 68
      y: 100
      pin_function: NO_FUNCTION
    - x: 79
      y: 100
      pin_function: PWM_IN
compatibility:
- name: LED
  action:
  - name: 'On'
    parameter:
    - name: Brightness
      constraint:
        min: 0
        max: 100
        unit: PERCENT
  - name: 'Off'
    parameter: []
  value: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LED_AH
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_LED_AH
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_LED_AH
  library_dependency: []
