id: MP-LED
brand: Maker Playground
model: LED
url: ''
type: MODULE
width: 124
height: 108
property: []
pin_template: GENERIC_PWM_ACTUATOR_3v3_5
connection_consume:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
      - x: 46
        y: 100
        ref_to: GND
      - x: 57
        y: 100
        ref_to: VCC
      - x: 68
        y: 100
        ref_to: NC
      - x: 79
        y: 100
        ref_to: SIG
compatibility:
- name: LED
  action:
  - name: 'On'
    parameter:
    - name: Brightness
      constraint:
        min: 0
        max: 100
        unit: PERCENT
  - name: 'Off'
    parameter: []
  value: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LED_AH
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_LED_AH
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_LED_AH
  library_dependency: []
