id: MP-HBridge
brand: Maker Playground
model: H-Bridge DC Motor Driver
url: ''
type: MODULE
formfactor: MP_DEVICE
width: 108
height: 250
property: []
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 37
      y: 226
      pin_function: GND
    - x: 48
      y: 226
      pin_function: VCC
    - x: 59
      y: 226
      pin_function: PWM_IN
    - x: 70
      y: 226
      pin_function: PWM_IN
compatibility:
- name: DC Motor
  action:
  - name: 'On'
    parameter:
    - name: Direction
      value: Forward
      constraint:
      - key: Forward
        value: 1
      - key: Backward
        value: 0
    - name: Speed
      constraint:
        min: 0
        max: 100
        unit: PERCENT
  value: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_HBRIDGE_DRIVER
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_HBRIDGE_DRIVER
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_HBRIDGE_DRIVER
  library_dependency: []
