id: Generic-MQ3
brand: Generic
model: MQ-3 alcohol sensor
url: https://www.arduinoall.com/product/261/%E0%B9%80%E0%B8%8B%E0%B8%99%E0%B9%80%E0%B8%8B%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B9%81%E0%B8%AD%E0%B8%A5%E0%B8%81%E0%B8%AD%E0%B8%AE%E0%B8%AD%E0%B8%A5%E0%B9%8C-mq-3-alcohol-sensor-alcohol
type: MODULE
width: 114
height: 182
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 5
  max_voltage: 5
  items:
  - name: VCC
    type: WIRE
    pins:
    - x: 35.1
      y: 171.7
      pin_function: VCC
  - name: GND
    type: WIRE
    pins:
    - x: 49.5
      y: 171.1
      pin_function: GND
  - name: A0
    type: WIRE
    pins:
    - x: 78.3
      y: 171.1
      pin_function: ANALOG_OUT
compatibility:
- name: Alcohol
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_MQ3
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_MQ3
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_MQ3
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_MQ3
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_MQ3
  library_dependency: []
