id: Raspberry-Pi-Camera-V1_3
brand: Raspberry Pi
model: Camera Board rev 1.3
url: https://www.raspberrypi.org/documentation/hardware/camera/
type: MODULE
width: 116
height: 114
pin_template: RPI_CAMERA
property:
- name: Camera Mode
  value: 640x480 42-60 fps
  # see more: https://picamera.readthedocs.io/en/release-1.13/fov.html#sensor-modes
  constraint:
    - key: 1920x1080 1-30 fps
      value: 1
    - key: 2592x1944 1-15 fps
      value: 2
    # - key: 2592x1944 1/6-1 fps
    #   value: 3
    - key: 1296x972 1-42 fps
      value: 4
    - key: 1294x730 1-49 fps
      value: 5
    - key: 640x480 42-60 fps
      value: 6
    - key: 640x480 60-90 fps
      value: 7
  datatype: STRING_INT_ENUM
  controltype: DROPDOWN
- name: Maximum Capture Rate (fps)
  value: 25
  datatype: DOUBLE
  controltype: SPINBOX
  constraint:
    min: 0.1
    max: 60
    unit: NOT_SPECIFIED
- name: Rotation
  value: 0
  datatype: INTEGER_ENUM
  controltype: DROPDOWN
  constraint:
    - 0
    - 90
    - 180
    - 270
connection_consume:
  - name: Camera
    type: CSI
    pins:
      - x: 17.5
        y: 0
        ref_to: CSI1
      - x: 22.9
        y: 0
        ref_to: CSI2
      - x: 28.3
        y: 0
        ref_to: CSI3
      - x: 33.7
        y: 0
        ref_to: CSI4
      - x: 39.1
        y: 0
        ref_to: CSI5
      - x: 44.5
        y: 0
        ref_to: CSI6
      - x: 49.9
        y: 0
        ref_to: CSI7
      - x: 55.3
        y: 0
        ref_to: CSI8
      - x: 60.7
        y: 0
        ref_to: CSI9
      - x: 66.1
        y: 0
        ref_to: CSI10
      - x: 71.5
        y: 0
        ref_to: CSI11
      - x: 76.9
        y: 0
        ref_to: CSI12
      - x: 82.3
        y: 0
        ref_to: CSI13
      - x: 87.7
        y: 0
        ref_to: CSI14
      - x: 92.1
        y: 0
        ref_to: CSI15
compatibility:
  - name: Camera
    value:
      - name: Image
        constraint: []
platforms:
- platform: RASPBERRYPI
  classname: MP_RPI_CAMERA
  library_dependency: []
