id: Generic-POT
brand: Generic
model: POT
url: ''
type: MODULE
width: 42
height: 85
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: VCC
    type: WIRE
    pins:
    - x: 7.2
      y: 86
      pin_function: VCC
  - name: SIG
    type: WIRE
    pins:
    - x: 21.6
      y: 86
      pin_function: ANALOG_OUT
  - name: GND
    type: WIRE
    pins:
    - x: 36
      y: 86
      pin_function: GND
compatibility:
- name: POT
  condition:
  - name: Compare
    parameter: []
  value:
  - name: Percent
    constraint:
      min: 0.0
      max: 100.0
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_TRIMPOT
  library_dependency: []
