id: SeeedStudio-101020341
brand: SeeedStudio
model: Grove - I2C Color Sensor V2
url: https://www.seeedstudio.com/Grove-I2C-Color-Sensor-V2.html
type: MODULE
width: 233
height: 130
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 15
      y: 48
      pin_function: GND
    - x: 15
      y: 59.3
      pin_function: VCC
    - x: 15
      y: 70.6
      pin_function: SDA
    - x: 15
      y: 81.9
      pin_function: SCL
compatibility:
- name: Color
  condition:
  - name: Compare
  - name: Detect Color
    parameter:
    - name: Color
      value: Red
      constraint:
      - key: Red
        value: 0
      - key: Green
        value: 1
      - key: Blue
        value: 2
      - key: Cyan
        value: 3
      - key: Magenta
        value: 4
      - key: Orange
        value: 5
      - key: Violet
        value: 6
      - key: White
        value: 7
      - key: Yellow
        value: 8
      - key: Black
        value: 9
  value:
  - name: Red
    constraint:
      min: 0
      max: 255
      unit: NOT_SPECIFIED
  - name: Green
    constraint:
      min: 0
      max: 255
      unit: NOT_SPECIFIED
  - name: Blue
    constraint:
      min: 0
      max: 255
      unit: NOT_SPECIFIED
  - name: Hue
    constraint:
      min: 0
      max: 360
      unit: NOT_SPECIFIED
  - name: Saturation
    constraint:
      min: 0
      max: 255
      unit: NOT_SPECIFIED
  - name: Value
    constraint:
      min: 0
      max: 255
      unit: NOT_SPECIFIED
platforms:
- platform: ARDUINO_AVR8
  classname: MP_TCS34725
  library_dependency:
  - SeeedStudio/Grove_I2C_Color_Sensor_TCS3472-master-2020-12-18
- platform: ARDUINO_ESP8266
  classname: MP_TCS34725
  library_dependency:
  - SeeedStudio/Grove_I2C_Color_Sensor_TCS3472-master-2020-12-18
- platform: ARDUINO_ESP32
  classname: MP_TCS34725
  library_dependency:
  - SeeedStudio/Grove_I2C_Color_Sensor_TCS3472-master-2020-12-18
- platform: ARDUINO_ATSAMD21
  classname: MP_TCS34725
  library_dependency:
  - SeeedStudio/Grove_I2C_Color_Sensor_TCS3472-master-2020-12-18
- platform: ARDUINO_ATSAMD51
  classname: MP_TCS34725
  library_dependency:
  - SeeedStudio/Grove_I2C_Color_Sensor_TCS3472-master-2020-12-18
