id: MP-Servo
brand: Maker Playground
model: SG90 Servo Motor
url: https://www.arduitronics.com/product/283/tower-pro-sg90-mini-micro-servo
type: MODULE
width: 188
height: 182
connection_consume:
  min_voltage: 5
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 45
      y: 164
      pin_function: GND
    - x: 50
      y: 164
      pin_function: VCC
    - x: 55
      y: 164
      pin_function: NO_FUNCTION
    - x: 60
      y: 164
      pin_function: PWM_IN
compatibility:
- name: Servo
  action:
  - name: Move To
    parameter:
    - name: Degree
      constraint:
        min: 0
        max: 180
        unit: DEGREE
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SERVO
  library_dependency:
  - arduino-libraries/Servo-1.1.7
- platform: ARDUINO_ESP8266
  classname: MP_SERVO
  library_dependency: []
