id: Generic-RGBLED-Module-CA
brand: Generic
model: RGB LED Module Common Anode
url: https://www.arduinoall.com/product/967/rgb-led-10mm-module-%E0%B9%82%E0%B8%A1%E0%B8%94%E0%B8%B9%E0%B8%A5-led-rgb-3-%E0%B8%AA%E0%B8%B5%E0%B8%82%E0%B8%99%E0%B8%B2%E0%B8%94-10mm
type: MODULE
width: 86
height: 107
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: R
    type: WIRE
    pins:
    - x: 35.144
      y: 90.968
      pin_function: PWM_IN
  - name: G
    type: WIRE
    pins:
    - x: 63.944
      y: 90.968
      pin_function: PWM_IN
  - name: B
    type: WIRE
    pins:
    - x: 49.544
      y: 90.968
      pin_function: PWM_IN
  - name: V
    type: WIRE
    pins:
    - x: 20.744
      y: 90.968
      pin_function: VCC
compatibility:
- name: RGB LED
  action:
  - name: 'On'
    parameter:
    - name: Red
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Green
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Blue
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Brightness
      constraint:
        min: 0
        max: 100
        unit: NOT_SPECIFIED
  - name: 'Off'
platforms:
- platform: ARDUINO_AVR8
  classname: MP_RGB_LED_CA
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_RGB_LED_CA
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_RGB_LED_CA
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_RGB_LED_CA
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_RGB_LED_CA
  library_dependency: []
