id: Generic-MAX30100
brand: Generic
model: MAX30100 pulse heart rate sensor HR module
url: 'https://www.allnewstep.com/product/1265/max30100-pulse-heart-rate-sensor-hr-module-%E0%B9%82%E0%B8%A1%E0%B8%94%E0%B8%B9%E0%B8%A5%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%8A%E0%B8%B5%E0%B8%9E%E0%B8%88%E0%B8%A3-%E0%B8%AD%E0%B8%B1%E0%B8%95%E0%B8%A3%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%80%E0%B8%95%E0%B9%89%E0%B8%99%E0%B8%AB%E0%B8%B1%E0%B8%A7%E0%B9%83%E0%B8%88'
type: MODULE
width: 103.0
height: 79.0
connection_consume:
  min_voltage: 1.8
  max_voltage: 3.3
  items:
  - name: VIN
    type: WIRE
    pins:
    - x: 8
      y: 72
      pin_function: VCC
  - name: SCL
    type: WIRE
    pins:
    - x: 22.4
      y: 72
      pin_function: SCL
  - name: SDA
    type: WIRE
    pins:
    - x: 36.8
      y: 72
      pin_function: SDA
  # - name: INT
  #   type: WIRE
  #   pins:
  #   - x: 51.2
  #     y: 72
  #     pin_function: INT
  # - name: IRD
  #   type: WIRE
  #   pins:
  #   - x: 65.6
  #     y: 72
  #     pin_function: ''
  # - name: RD
  #   type: WIRE
  #   pins:
  #   - x: 80
  #     y: 72
  #     pin_function: ''
  - name: GND
    type: WIRE
    pins:
    - x: 94.4
      y: 72
      pin_function: GND
compatibility:
- name: Pulse Oximetry
  condition:
    - name: Compare
      funcname: ''
  value:
    - name: Heart Rate
      dataType: DOUBLE
      constraint:
        min: 0
        max: 300
        unit: BPM
    - name: SpO2
      dataType: INTEGER
      constraint:
        min: 0
        max: 100
        unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_MAX30100
  library_dependency:
    - oxullo/Arduino-MAX30100-1.2.1
- platform: ARDUINO_ESP8266
  classname: MP_MAX30100
  library_dependency:
    - oxullo/Arduino-MAX30100-1.2.1
- platform: ARDUINO_ESP32
  classname: MP_MAX30100
  library_dependency:
    - oxullo/Arduino-MAX30100-1.2.1
- platform: ARDUINO_ATSAMD21
  classname: MP_MAX30100
  library_dependency:
    - oxullo/Arduino-MAX30100-1.2.1
- platform: ARDUINO_ATSAMD51
  classname: MP_MAX30100
  library_dependency:
    - oxullo/Arduino-MAX30100-1.2.1