id: SeeedStudio-107020001
brand: SeeedStudio
model: Grove - Speaker
url: https://www.seeedstudio.com/Grove-Speaker-p-1445.html
type: MODULE
width: 311
height: 176
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 43
      y: 65
      pin_function: GND
    - x: 43
      y: 79.4
      pin_function: VCC
    - x: 43
      y: 93.8
      pin_function: NO_FUNCTION
    - x: 43
      y: 108.2
      pin_function: PWM_IN
compatibility:
- name: Buzzer
  action:
  - name: Play Tone
    parameter:
    - name: Tone Frequency
      constraint:
        min: 0
        max: 20000
        unit: HERTZ
    - name: Duration
      constraint:
        min: 0
        max: 1000
        unit: SECOND
  - name: Beep
platforms:
- platform: ARDUINO_AVR8
  classname: MP_BUZZER
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_BUZZER
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_BUZZER
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_BUZZER
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_BUZZER
  library_dependency: []
