id: MP-LoadDriver
brand: Maker Playground
model: Load Driver
url: ''
type: MODULE
formfactor: MP_DEVICE
width: 124
height: 108
property: []
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 46
      y: 101
      pin_function: GND
    - x: 57
      y: 101
      pin_function: VCC
    - x: 68
      y: 101
      pin_function: NO_FUNCTION
    - x: 79
      y: 101
      pin_function: DIGITAL_IN
compatibility:
- name: Load Driver
  action:
  - name: 'On'
    parameter: []
  - name: 'Off'
    parameter: []
  value: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LOAD_DRIVER_AH
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_LOAD_DRIVER_AH
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_LOAD_DRIVER_AH
  library_dependency: []
