id: SeeedStudio-101020044
brand: SeeedStudio
model: Grove - Alcohol Sensor
url: https://www.seeedstudio.com/Grove-Gas-Sensor-MQ3.html
type: MODULE
width: 312
height: 176
connection_consume:
  min_voltage: 5
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 27
      y: 64
      pin_function: GND
    - x: 27
      y: 78.4
      pin_function: VCC
    - x: 27
      y: 92.8
      pin_function: DIGITAL_IN
    - x: 27
      y: 107.2
      pin_function: ANALOG_OUT
compatibility:
- name: Alcohol
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_MQ303A
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_MQ303A
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_MQ303A
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_MQ303A
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_MQ303A
  library_dependency: []
