id: Generic-SCT013
brand: Generic
model: Non-invasive AC Current Sensor (30A max)
url: ''
type: MODULE
width: 230
height: 404
property: []
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 171
      y: 404
      pin_function: GND
    - x: 171
      y: 404
      pin_function: VCC
    - x: 171
      y: 404
      pin_function: NO_FUNCTION
    - x: 171
      y: 404
      pin_function: ANALOG_OUT
compatibility:
- name: Current
  condition:
  - name: Compare
  value:
  - name: Ampere
    constraint:
      min: 0
      max: 30
      unit: AMPERE
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SCT013_30A
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_SCT013_30A_ESP32
  library_dependency: []
