id: M5Stack-ToFHat
brand: M5Stack
model: M5StickC ToF HAT
url: https://m5stack.com/products/m5stickc-tof-hatvl53l0x
type: MODULE
width: 136
height: 96
connection_consume:
  min_voltage: 3.3
  max_voltage: 3.3
  items:
  - name: HAT
    type: M5HAT
    pins:
    - x: 118.4
      y: 96
      pin_function: GND
    - x: 104
      y: 96
      pin_function: NO_FUNCTION
    - x: 89.6
      y: 96
      pin_function: SW_SERIAL_RX
    - x: 75.2
      y: 96
      pin_function: NO_FUNCTION
    - x: 60.8
      y: 96
      pin_function: SW_SERIAL_TX
    - x: 46.4
      y: 96
      pin_function: NO_FUNCTION
    - x: 32
      y: 96
      pin_function: VCC
    - x: 17.6
      y: 96
      pin_function: NO_FUNCTION
compatibility:
- name: Distance
  condition:
    - name: Compare
  value:
    - name: Distance
      constraint:
        min: 0.3
        max: 120
        unit: CENTIMETER
#  property:
#    - name: Mode
#      datatype: STRING_INT_ENUM
#      optional: true
#      controltype: DROPDOWN
#      value: High Accuracy
#      constraint:
#        - key: High Accuracy
#          value: 0
#        - key: High Speed
#          value: 1
#    - name: Use Long Range
#      datatype: STRING_INT_ENUM
#      optional: true
#      controltype: DROPDOWN
#      value: 'Yes'
#      constraint:
#        - key: 'Yes'
#          value: 1
#        - key: 'No'
#          value: 0
platforms:
- platform: ARDUINO_ESP32
  classname: MP_VL53L0X_M5ToFHAT
  library_dependency:
    - pololu/vl53l0x-arduino-1.3.0
