id: MP-Distance
brand: Maker Playground
model: Distance/Gesture
url: ''
type: MODULE
width: 124
height: 108
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 79
      y: 109
      pin_function: GND
    - x: 68
      y: 109
      pin_function: VCC
    - x: 57
      y: 109
      pin_function: SDA
    - x: 46
      y: 109
      pin_function: SCL
compatibility:
- name: Distance
  condition:
  - name: Compare
  value:
  - name: Distance
    constraint:
      min: 10
      max: 20
      unit: CENTIMETER
platforms:
- platform: ARDUINO_AVR8
  classname: MP_APDS9960
  library_dependency:
  - SparkFun/SparkFun_APDS-9960_Sensor_Arduino_Library
- platform: ARDUINO_ESP8266
  classname: MP_APDS9960
  library_dependency:
  - SparkFun/SparkFun_APDS-9960_Sensor_Arduino_Library
- platform: ARDUINO_ESP32
  classname: MP_APDS9960
  library_dependency:
  - SparkFun/SparkFun_APDS-9960_Sensor_Arduino_Library
