id: Azure-IotHub
brand: Azure
model: IotHub
url: 'https://azure.microsoft.com/en-us/services/iot-hub/'
type: VIRTUAL
formfactor: NONE
cloud_platform: AZURE
width: 0.0
height: 0.0
property:
  - name: Key
    datatype: AZURE_IOTHUB_KEY
    controltype: AZURE_WIZARD
    value: ''
    constraint: []
pin_template: NO_PIN
connection_consume: []
compatibility:
  - name: Telemetry
    action:
      - name: Send Telemetry
        parameter:
          - name: data
platforms:
- platform: ARDUINO_ESP8266
  classname: MP_Azure_IoTHub_ESP8266
  library_dependency:
  - Azure/azure-iot-arduino-1.0.45
  - Azure/azure-iot-arduino-protocol-mqtt-1.0.45
  - Azure/azure-iot-arduino-utility-1.0.45
