id: MP-Soil
brand: Maker Playground
model: Soil-Moisture Sensor
url: ''
type: MODULE
width: 124
height: 330
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 42
      y: 323
      pin_function: GND
    - x: 55
      y: 323
      pin_function: VCC
    - x: 68
      y: 323
      pin_function: DIGITAL_IN
    - x: 81
      y: 323
      pin_function: ANALOG_OUT
compatibility:
- name: Soil Moisture
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SOIL_MOISTURE_W_EN
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_SOIL_MOISTURE_W_EN
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_SOIL_MOISTURE_W_EN
  library_dependency: []
