id: KMM-RS0102
brand: KMM
model: RS0102 Temperature & Humidity remote sensor (AM2305)
url: http://komomi.net/wp-content/uploads/2019/09/KMM-RS0102-Temp-Humi-Sensor.pdf
type: MODULE
width: 1453
height: 378
property:
- name: device id
  datatype: INTEGER_ENUM
  controltype: DROPDOWN
  value: 1
  constraint:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
connection_consume:
  min_voltage: 12
  max_voltage: 12
  items:
  - name: B(-)
    type: WIRE
    pins:
    - x: 1449.0
      y: 179.0
      voltage_level: LEVEL_12
      pin_function: RS485_Negative
  - name: A(+)
    type: WIRE
    pins:
    - x: 1449.0
      y: 161.0
      voltage_level: LEVEL_12
      pin_function: RS485_Positive
  - name: GND
    type: WIRE
    pins:
    - x: 1449.0
      y: 216.0
      voltage_level: LEVEL_12
      pin_function: GND
  - name: VCC
    type: WIRE
    pins:
    - x: 1449.0
      y: 198.0
      voltage_level: LEVEL_12
      pin_function: VCC
compatibility:
- name: Temperature
  condition:
  - name: Compare
  value:
  - name: Temperature
    constraint:
      min: -40.0
      max: 80.0
      unit: CELSIUS
- name: Humidity
  condition:
  - name: Compare
  value:
  - name: Humidity
    constraint:
      min: 0.0
      max: 100.0
      unit: PERCENT
platforms:
- platform: ARDUINO_ESP32
  classname: KMM_RS0102
  library_dependency:
  - 4-20ma/ModbusMaster-2.0.1
