id: Generic-TRIMPOT
brand: Generic
model: TRIMPOT
url: ''
type: MODULE
width: 36
height: 48
need_breadboard: true
breadboard_placement: TWO_SIDES
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: VCC
    type: WIRE
    pins:
    - x: 4
      y: 46.2
      pin_function: VCC
  - name: SIG
    type: WIRE
    pins:
    - x: 18.4
      y: 3
      pin_function: ANALOG_OUT
  - name: GND
    type: WIRE
    pins:
    - x: 32.8
      y: 46.2
      pin_function: GND
compatibility:
- name: POT
  condition:
  - name: Compare
    parameter: []
  value:
  - name: Percent
    constraint:
      min: 0.0
      max: 100.0
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_TRIMPOT
  library_dependency: []
