id: Grove-101020132
brand: SeeedStudio
model: Grove - Light Sensor v1.2 - LS06-S phototransistor
url: https://www.seeedstudio.com/Grove-Light-Sensor-v1.2-p-2727.html
type: MODULE
width: 112
height: 134
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 19
      y: 49
      pin_function: GND
    - x: 19
      y: 60.3
      pin_function: VCC
    - x: 19
      y: 71.6
      pin_function: NO_FUNCTION
    - x: 19
      y: 82.9
      pin_function: ANALOG_OUT
compatibility:
- name: Light
  condition:
  - name: Compare
    parameter: []
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LIGHT_SENSOR
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_LIGHT_SENSOR
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_LIGHT_SENSOR
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_LIGHT_SENSOR
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_LIGHT_SENSOR
  library_dependency: []
