id: SeeedStudio-103020008
brand: SeeedStudio
model: Grove - MOSFET for Arduino
url: https://www.seeedstudio.com/Grove-MOSFET.html
type: MODULE
width: 242
height: 137
connection_consume:
  min_voltage: 5
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 18
      y: 53
      pin_function: GND
    - x: 18
      y: 64.3
      pin_function: VCC
    - x: 18
      y: 75.6
      pin_function: NO_FUNCTION
    - x: 18
      y: 86.9
      pin_function: DIGITAL_IN
compatibility:
- name: Load Driver
  action:
  - name: 'On'
  - name: 'Off'
platforms:
- platform: ARDUINO_AVR8
  classname: MP_RELAY
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_RELAY
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_RELAY
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_RELAY
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_RELAY
  library_dependency: []
