id: Grove-104020048
brand: SeeedStudio
model: Grove Chainable RGB Led V2.0
url: https://www.seeedstudio.com/Grove-Chainable-RGB-Led-V2-0.html
type: MODULE
width: 134
height: 238
property:
- name: Led Count
  datatype: INTEGER
  controltype: SPINBOX
  value: 1
  constraint:
    min: 1
    max: 10000
    unit: NOT_SPECIFIED
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 84
      y: 238
      pin_function: GND
    - x: 72.67
      y: 238
      pin_function: VCC
    - x: 61.33
      y: 238
      pin_function:
      - DIGITAL_OUT
      - DIGITAL_IN
    - x: 50
      y: 238
      pin_function:
      - DIGITAL_OUT
      - DIGITAL_IN
compatibility:
- name: RGB LED Strip
  action:
  - name: Set Color
    parameter:
    - name: Index
    - name: Red
    - name: Green
    - name: Blue
  - name: Fill Color
    parameter:
    - name: Start Index
    - name: End Index
    - name: Red
    - name: Green
    - name: Blue
  - name: Set Brightness
    parameter:
    - name: Brightness
  - name: Clear
    parameter: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_CHAINABLELED_P9813
  library_dependency:
  - pjpmarques/ChainableLED-1.3
- platform: ARDUINO_ESP8266
  classname: MP_CHAINABLELED_P9813
  library_dependency:
  - pjpmarques/ChainableLED-1.3
- platform: ARDUINO_ESP32
  classname: MP_CHAINABLELED_P9813
  library_dependency:
  - pjpmarques/ChainableLED-1.3
- platform: ARDUINO_ATSAMD21
  classname: MP_CHAINABLELED_P9813
  library_dependency:
  - pjpmarques/ChainableLED-1.3
- platform: ARDUINO_ATSAMD51
  classname: MP_CHAINABLELED_P9813
  library_dependency:
  - pjpmarques/ChainableLED-1.3
- platform: MICROPYTHON_K210
  classname: MP_CHAINABLELED_P9813
  library_dependency: []
