id: Generic-TM1637
brand: Generic
model: 4-digit 7-Segment display LED module 0.36"
url: https://www.arduitronics.com/product/220/seven-segment-4-digit-clock-display-0-36-inches-catalex
type: MODULE
width: 153
height: 372
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: CLK
    type: WIRE
    pins:
    - x: 99.5
      y: 321
      pin_function:
      - DIGITAL_OUT
      - DIGITAL_IN
  - name: DIO
    type: WIRE
    pins:
    - x: 85.1
      y: 321
      pin_function:
      - DIGITAL_OUT
      - DIGITAL_IN
  - name: VCC
    type: WIRE
    pins:
    - x: 70.7
      y: 321
      pin_function: VCC
  - name: GND
    type: WIRE
    pins:
    - x: 56.3
      y: 321
      pin_function: GND
compatibility:
- name: 7 Segment
  action:
  - name: Show Number
    parameter:
    - name: Number
      constraint:
        min: -999
        max: 9999
        unit: NOT_SPECIFIED
  - name: Show Two Numbers with Colon
    parameter:
    - name: Before colon
      constraint:
        min: -9
        max: 99
        unit: NOT_SPECIFIED
    - name: After colon
      constraint:
        min: -9
        max: 99
        unit: NOT_SPECIFIED
  - name: 'Off'
platforms:
- platform: ARDUINO_AVR8
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ESP32
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ESP8266
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ATSAMD21
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ATSAMD51
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
