id: Generic-DHT12
brand: Generic
model: DHT12 Humidity Temperature Sensor Module
url: https://www.arduitronics.com/product/1705/dht12-humidity-temperature-sensor-module-free-cable-i2c-interface
type: MODULE
width: 72
height: 72
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: VIN
    type: WIRE
    pins:
    - x: 14.5
      y: 69
      pin_function: VCC
  - name: SDA
    type: WIRE
    pins:
    - x: 28.9
      y: 69
      pin_function: SDA
  - name: GND
    type: WIRE
    pins:
    - x: 43.3
      y: 69
      pin_function: GND
  - name: SCL
    type: WIRE
    pins:
    - x: 57.7
      y: 69
      pin_function: SCL
compatibility:
- name: Temperature
  condition:
  - name: Compare
  value:
  - name: Temperature
    constraint:
      min: 0
      max: 50
      unit: CELSIUS
- name: Humidity
  condition:
  - name: Compare
  value:
  - name: Humidity
    constraint:
      min: 20
      max: 80
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_DHT12
  library_dependency:
  - dplasa/dht
