id: SeeedStudio-101020010
brand: SeeedStudio
model: Grove - Ultrasonic Ranger
url: https://www.seeedstudio.com/Grove-Ultrasonic-Distance-Sensor.html
type: MODULE
width: 226
height: 114
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 96.38
      y: 98.3
      pin_function: GND
    - x: 107.72
      y: 98.3
      pin_function: VCC
    - x: 119.06
      y: 98.3
      pin_function: NO_FUNCTION
    - x: 130.4
      y: 98.3
      pin_function: DIGITAL_IN
compatibility:
- name: Distance
  condition:
  - name: Compare
  value:
  - name: Distance
    constraint:
      min: 2
      max: 450
      unit: CENTIMETER
platforms:
- platform: ARDUINO_AVR8
  classname: MP_GROVE_ULTRASONIC_RANGER
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_GROVE_ULTRASONIC_RANGER
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_GROVE_ULTRASONIC_RANGER
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_GROVE_ULTRASONIC_RANGER
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_GROVE_ULTRASONIC_RANGER
  library_dependency: []
