id: DFRobot-MP3-TF-16P
brand: DFRobot
model: MP3-TF-16P Mini MP3 Player Module
url: https://www.arduinoall.com/product/989/dfplayer-mp3-tf-16p-mini-mp3-player-module-for-arduino-%E0%B9%82%E0%B8%A1%E0%B8%94%E0%B8%B9%E0%B8%A5%E0%B9%80%E0%B8%A5%E0%B9%88%E0%B8%99%E0%B9%80%E0%B8%9E%E0%B8%A5%E0%B8%87-mp3-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A-arduino
type: MODULE
width: 182
height: 127
need_breadboard: true
breadboard_placement: TWO_SIDES
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: RX
    type: WIRE
    pins:
    - x: 0
      y: 107.07
      pin_function: SW_SERIAL_RX
  - name: TX
    type: WIRE
    pins:
    - x: 100.8
      y: 107.07
      pin_function: SW_SERIAL_TX
  - name: VCC
    type: WIRE
    pins:
    - x: 72
      y: 107.07
      pin_function: VCC
  - name: GND
    type: WIRE
    pins:
    - x: 158.4
      y: 107.07
      pin_function: GND
# TODO: implement the pin_template for this device
# connection_provide:
#   voltage_level: LEVEL_5
#   items:
#   - name: NC
#     type: WIRE
#     pins:
#     - x: 72
#       y: 6.29
#       ref_to: NC
compatibility:
  - name: MP3 Player
    action:
      - name: Play MP3 by index
        parameter:
        - name: Index
          value: 1
          constraint:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
      - name: Play Next MP3
      - name: Play Previous MP3
      - name: Pause
      - name: Start from pause
      - name: Enable Loop
      - name: Enable Loop All
      - name: Disable Loop
      - name: Disable Loop All
      - name: Set Volume
        parameter: 
          - name: volume
            constraint:
              min: 0
              max: 100
              unit: PERCENT
      - name: Volume Up
      - name: Volume Down
      - name: Set EQ
        parameter:
          - name: EQ
            value: NORMAL
            constraint:
              - key: NORMAL
                value: 0
              - key: POP
                value: 1
              - key: ROCK
                value: 2
              - key: JAZZ
                value: 3
              - key: CLASSIC
                value: 4
              - key: BASS
                value: 5
    value:
      - name: Volume
        constraint:
          min: 0
          max: 100
          unit: PERCENT
      - name: FileCount
        constraint:
          min: 0
          max: 65535
          unit: NOT_SPECIFIED
      - name: CurrentFileNumber
        constraint:
          min: 0
          max: 65535
          unit: NOT_SPECIFIED
platforms:
- platform: ARDUINO_AVR8
  classname: MP_DF_MP3_PLAYER
  library_dependency:
  - DFRobot/DFRobotDFPlayerMini-1.0.5
