id: MP-Acc-V1
brand: Maker Playground
model: Accelerometer v1.0
url: ''
type: MODULE
width: 171
height: 114
pin_template: GENERIC_I2C_DEVICE_3v3_5
connection_consume:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
      - x: 69
        y: 0
        ref_to: GND
      - x: 80
        y: 0
        ref_to: VCC
      - x: 91
        y: 0
        ref_to: SDA
      - x: 102
        y: 0
        ref_to: SCL
compatibility:
  - name: Accelerometer
    condition:
      - name: Compare
    value:
      - name: Accel_X
        constraint:
          min: -100
          max: 100
          unit: METERPERSECSQUARE
      - name: Accel_Y
        constraint:
          min: -100
          max: 100
          unit: METERPERSECSQUARE
      - name: Accel_Z
        constraint:
          min: -100
          max: 100
          unit: METERPERSECSQUARE
      - name: Accel_Magnitude
        constraint:
          min: 0
          max: 100
          unit: METERPERSECSQUARE
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LIS3DH
  library_dependency:
    - adafruit/Adafruit_LIS3DH-1.0.4
    - adafruit/Adafruit_Sensor-1.1.4
- platform: ARDUINO_ESP8266
  classname: MP_LIS3DH
  library_dependency:
    - adafruit/Adafruit_LIS3DH-1.0.4
    - adafruit/Adafruit_Sensor-1.1.4
- platform: ARDUINO_ESP32
  classname: MP_LIS3DH
  library_dependency:
    - adafruit/Adafruit_LIS3DH-1.0.4
    - adafruit/Adafruit_Sensor-1.1.4
