id: MP-Acc-V1
brand: Maker Playground
model: Accelerometer v1.0
url: ''
type: MODULE
width: 171
height: 114
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 69
      y: 0
      pin_function: GND
    - x: 80
      y: 0
      pin_function: VCC
    - x: 91
      y: 0
      pin_function: SDA
    - x: 102
      y: 0
      pin_function: SCL
compatibility:
- name: Accelerometer
  condition:
  - name: Compare
  value:
  - name: Accel_X
    constraint:
      min: -100
      max: 100
      unit: METERPERSECSQUARE
  - name: Accel_Y
    constraint:
      min: -100
      max: 100
      unit: METERPERSECSQUARE
  - name: Accel_Z
    constraint:
      min: -100
      max: 100
      unit: METERPERSECSQUARE
  - name: Accel_Magnitude
    constraint:
      min: 0
      max: 100
      unit: METERPERSECSQUARE
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LIS3DH
  library_dependency:
  - adafruit/Adafruit_LIS3DH-1.0.4
  - adafruit/Adafruit_Sensor-1.1.4
- platform: ARDUINO_ESP8266
  classname: MP_LIS3DH
  library_dependency:
  - adafruit/Adafruit_LIS3DH-1.0.4
  - adafruit/Adafruit_Sensor-1.1.4
- platform: ARDUINO_ESP32
  classname: MP_LIS3DH
  library_dependency:
  - adafruit/Adafruit_LIS3DH-1.0.4
  - adafruit/Adafruit_Sensor-1.1.4
