id: SeeedStudio-101020049
brand: SeeedStudio
model: Grove - Flame Sensor
url: https://www.seeedstudio.com/catalog/product/view/id/1430/s/Grove-Flame-Sensor
type: MODULE
width: 134
height: 170
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 33
      y: 99
      pin_function: GND
    - x: 33
      y: 110.33
      pin_function: VCC
    - x: 33
      y: 121.67
      pin_function: NO_FUNCTION
    - x: 33
      y: 133
      pin_function: ANALOG_OUT
compatibility:
- name: Flame
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_FLYINGFISH_FLAME_DETECTOR
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_FLYINGFISH_FLAME_DETECTOR
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_FLYINGFISH_FLAME_DETECTOR
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_FLYINGFISH_FLAME_DETECTOR
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_FLYINGFISH_FLAME_DETECTOR
  library_dependency: []
