id: MP-ESP32
brand: Maker Playground
model: NodeMCU-32S Breakout Board
url: ''
type: CONTROLLER
pio_boardid: nodemcu-32s
cloud_provide:
  - cloud_platform: NETPIE
    classname: MP_NETPIE_ESP
    library_dependency:
      - lamloei/ESP32_Microgear
width: 289
height: 363.8
pin_template: ESP_32
connection_provide:
  - name: D1
    type: MAKER_PLAYGROUND
    pins:
      - x: 282
        y: 232
        ref_to: GND
      - x: 282
        y: 221
        ref_to: VCC
      - x: 282
        y: 210
        ref_to: "18"
      - x: 282
        y: 199
        ref_to: "19"
  - name: D2
    type: MAKER_PLAYGROUND
    pins:
      - x: 282
        y: 301
        ref_to: GND
      - x: 282
        y: 290
        ref_to: VCC
      - x: 282
        y: 279
        ref_to: "16"
      - x: 282
        y: 268
        ref_to: "17"
  - name: D3
    type: MAKER_PLAYGROUND
    pins:
      - x: 10
        y: 266
        ref_to: GND
      - x: 10
        y: 277
        ref_to: VCC
      - x: 10
        y: 288
        ref_to: "NF"
      - x: 10
        y: 299
        ref_to: "13"
  - name: D4
    type: MAKER_PLAYGROUND
    pins:
      - x: 10
        y: 199
        ref_to: GND
      - x: 10
        y: 210
        ref_to: VCC
      - x: 10
        y: 221
        ref_to: "NF"
      - x: 10
        y: 232
        ref_to: "14"
  - name: D5
    type: MAKER_PLAYGROUND
    pins:
      - x: 10
        y: 130
        ref_to: GND
      - x: 10
        y: 141
        ref_to: VCC
      - x: 10
        y: 152
        ref_to: "NF"
      - x: 10
        y: 163
        ref_to: "27"
  - name: D6
    type: MAKER_PLAYGROUND
    pins:
      - x: 10
        y: 62
        ref_to: GND
      - x: 10
        y: 73
        ref_to: VCC
      - x: 10
        y: 84
        ref_to: "NF"
      - x: 10
        y: 95
        ref_to: "27"
  - name: A1
    type: MAKER_PLAYGROUND
    pins:
      - x: 125
        y: 19
        ref_to: GND
      - x: 114
        y: 19
        ref_to: VCC
      - x: 103
        y: 19
        ref_to: "NF"
      - x: 92
        y: 19
        ref_to: "34"
  - name: A2
    type: MAKER_PLAYGROUND
    pins:
      - x: 196
        y: 19
        ref_to: GND
      - x: 185
        y: 19
        ref_to: VCC
      - x: 174
        y: 19
        ref_to: "NF"
      - x: 163
        y: 19
        ref_to: "35"
  - name: I2C (#1)
    type: MAKER_PLAYGROUND
    pins:
      - x: 282
        y: 95
        ref_to: GND
      - x: 282
        y: 84
        ref_to: VCC
      - x: 282
        y: 73
        ref_to: "21"
        function: SDA
      - x: 282
        y: 62
        ref_to: "22"
        function: SCL
  - name: I2C (#2)
    type: MAKER_PLAYGROUND
    pins:
      - x: 282
        y: 163
        ref_to: GND
      - x: 282
        y: 152
        ref_to: VCC
      - x: 282
        y: 141
        ref_to: "21"
        function: SDA
      - x: 282
        y: 130
        ref_to: "22"
        function: SCL
compatibility: []
platforms:
- platform: ARDUINO_ESP32
  classname: ''
  library_dependency: []
