id: M5Stack-Angle
brand: M5Stack
model: Angle
url: https://docs.m5stack.com/#/en/unit/angle
type: MODULE
width: 138
height: 184
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 52.5
      y: 178
      pin_function: GND
    - x: 64
      y: 178
      pin_function: VCC
    - x: 75
      y: 178
      pin_function: NO_FUNCTION
    - x: 86.5
      y: 178
      pin_function: ANALOG_OUT
compatibility:
- name: POT
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_ESP32
  classname: MP_TRIMPOT
  library_dependency: []
