id: LogiSenses-Senses_Weizen
brand: LogiSenses
model: Senses Weizen
url: https://www.sensesiot.com
type: CONTROLLER
pio_boardid: esp32dev
cloud_provide:
- cloud_platform: NETPIE
  classname: MP_NETPIE_ESP
  library_dependency:
  - lamloei/ESP32_Microgear
- cloud_platform: BLYNK
  classname: MP_BLYNK_NODEMCU
  library_dependency:
  - blynkkk/Blynk-0.6.1
- cloud_platform: AZURE
  classname: MP_AZURE_ESP
  library_dependency: []
- cloud_platform: REST
  classname: MP_REST_ESP
  library_dependency: []
pin_template: ESP_32
width: 369
height: 174
property: []
connection_provide:
  - name: VCC0
    type: WIRE
    pins:
      - x: 51     
        y: 26
        ref_to: VCC
  - name: "21"
    type: WIRE
    pins:
      - x: 66
        y: 26
        ref_to: "21"
  - name: "22"
    type: WIRE
    pins:
      - x: 80
        y: 26
        ref_to: "22"
  - name: "33"
    type: WIRE
    pins:
      - x: 94
        y: 26
        ref_to: "33"
  - name: GND0
    type: WIRE
    pins:
      - x: 109
        y: 26
        ref_to: GND
  - name: "25"
    type: WIRE
    pins:
      - x: 123
        y: 26
        ref_to: "25"
  - name: "27"
    type: WIRE
    pins:
      - x: 138
        y: 26
        ref_to: "27"
  - name: "14"
    type: WIRE
    pins:
      - x: 152
        y: 26
        ref_to: "14"
  - name: VCC1
    type: WIRE
    pins:
      - x: 167
        y: 26
        ref_to: VCC
  - name: "23"
    type: WIRE
    pins:
      - x: 180
        y: 26
        ref_to: "23"
  - name: "19"
    type: WIRE
    pins:
      - x: 195
        y: 26
        ref_to: "19"
  - name: "18"
    type: WIRE
    pins:
      - x: 210
        y: 26
        ref_to: "18"
  - name: GND1
    type: WIRE
    pins:
      - x: 224
        y: 26
        ref_to: GND
  - name: "39"
    type: WIRE
    pins:
      - x: 310        
        y: 26
        ref_to: "39"
  - name: GND2
    type: WIRE
    pins:
      - x: 325        
        y: 26
        ref_to: GND
  - name: VIN0
    type: WIRE
    pins:
      - x: 51
        y: 12        
        ref_to: VIN
  - name: VIN1
    type: WIRE
    pins:
      - x: 66
        y: 12
        ref_to: VIN
  - name: GND3
    type: WIRE
    pins:
      - x: 80
        y: 12
        ref_to: GND
  - name: "32"
    type: WIRE
    pins:
      - x: 94
        y: 12
        ref_to: "32"
  - name: "34"
    type: WIRE
    pins:
      - x: 109
        y: 12        
        ref_to: "34"
  - name: "26"
    type: WIRE
    pins:
      - x: 123
        y: 12        
        ref_to: "26"
  - name: "GND4"
    type: WIRE
    pins:
      - x: 138
        y: 12
        ref_to: "GND"
  - name: "13"
    type: WIRE
    pins:
      - x: 152
        y: 12
        ref_to: "13"
  - name: "15"
    type: WIRE
    pins:
      - x: 167
        y: 12
        ref_to: "15"
  - name: "GND5"
    type: WIRE
    pins:
      - x: 180
        y: 12
        ref_to: "GND"
  - name: "0"
    type: WIRE
    pins:
      - x: 195
        y: 12
        ref_to: "0"
  - name: "5"
    type: WIRE
    pins:
      - x: 210
        y: 12
        ref_to: "5"
  - name: "4"
    type: WIRE
    pins:
      - x: 224
        y: 12
        ref_to: "4"
  - name: "GND6"
    type: WIRE
    pins:
      - x: 253
        y: 12
        ref_to: "GND"
  - name: "GND7"
    type: WIRE
    pins:
      - x: 282
        y: 12
        ref_to: "GND"
  - name: "36"
    type: WIRE
    pins:
      - x: 310
        y: 12
        ref_to: "36"
  - name: "35"
    type: WIRE
    pins:
      - x: 325
        y: 12
        ref_to: "35"
integrated_devices:
- name: Built in IO2
  pin_template: GENERIC_DIGITAL_ACTUATOR_3v3
  integrated_connection:
    - ref_to: SIG
      host_ref_to: "2"
    - ref_to: GND
      host_ref_to: GND
  compatibility:
    - name: LED
      action:
        - name: 'On'
          parameter:
            - name: Brightness
              constraint:
                min: 0.0
                max: 100.0
                unit: PERCENT
        - name: 'Off'
  platforms:
    - platform: ARDUINO_ESP32
      classname: MP_LED_AH
      library_dependency: []
platforms:
- platform: ARDUINO_ESP32
  classname: ''
  library_dependency: []
