id: SeeedStudio-102010228
brand: SeeedStudio
model: Lotus Cortex-M0+
url: https://www.seeedstudio.com/Seeeduino-Lotus-Cortex-M0-p-2896.html
type: CONTROLLER
pio_boardid: seeed_zero
width: 388
height: 302
property: []
pin_template: SEEEDUINO_ZERO
connection_provide:
  - name: '0'
    type: WIRE
    pins:
      - x: 358.67
        y: 14.4
        ref_to: D0
  - name: '1'
    type: WIRE
    pins:
      - x: 344.27
        y: 14.4
        ref_to: D1
  - name: '2'
    type: WIRE
    pins:
      - x: 329.87
        y: 14.4
        ref_to: D2
  - name: '3'
    type: WIRE
    pins:
      - x: 315.47
        y: 14.4
        ref_to: D3
  - name: '4'
    type: WIRE
    pins:
      - x: 301.07
        y: 14.4
        ref_to: D4
  - name: '5'
    type: WIRE
    pins:
      - x: 286.67
        y: 14.4
        ref_to: D5
  - name: '6'
    type: WIRE
    pins:
      - x: 272.27
        y: 14.4
        ref_to: D6
  - name: '7'
    type: WIRE
    pins:
      - x: 257.87
        y: 14.4
        ref_to: D7

  - name: '8'
    type: WIRE
    pins:
      - x: 234.46
        y: 14.4
        ref_to: D8
  - name: '9'
    type: WIRE
    pins:
      - x: 220.06
        y: 14.4
        ref_to: D9
  - name: '10'
    type: WIRE
    pins:
      - x: 205.66
        y: 14.4
        ref_to: D10
  - name: '11'
    type: WIRE
    pins:
      - x: 191.26
        y: 14.4
        ref_to: D11
  - name: '12'
    type: WIRE
    pins:
      - x: 176.86
        y: 14.4
        ref_to: D12
  - name: '13'
    type: WIRE
    pins:
      - x: 162.46
        y: 14.4
        ref_to: D13
  - name: GND0
    type: WIRE
    pins:
      - x: 148.06
        y: 14.4
        ref_to: GND
  - name: SDA
    type: WIRE
    pins:
      - x: 119.26
        y: 14.4
        ref_to: SDA
  - name: SCL
    type: WIRE
    pins:
      - x: 104.86
        y: 14.4
        ref_to: SCL

  - name: 3.3V
    type: WIRE
    pins:
      - x: 200.47
        y: 288
        ref_to: VCC
  - name: 5V
    type: WIRE
    pins:
      - x: 214.87
        y: 288
        ref_to: VCC
        voltage_level: LEVEL_5
  - name: GND1
    type: WIRE
    pins:
      - x: 229.27
        y: 288
        ref_to: GND
  - name: GND2
    type: WIRE
    pins:
      - x: 243.67
        y: 288
        ref_to: GND

  - name: A0
    type: WIRE
    pins:
      - x: 287.05
        y: 288
        ref_to: A0
  - name: A1
    type: WIRE
    pins:
      - x: 301.45
        y: 288
        ref_to: A1
  - name: A2
    type: WIRE
    pins:
      - x: 315.85
        y: 288
        ref_to: A2
  - name: A3
    type: WIRE
    pins:
      - x: 330.25
        y: 288
        ref_to: A3
  - name: A4
    type: WIRE
    pins:
      - x: 344.65
        y: 288
        ref_to: A4
  - name: A5
    type: WIRE
    pins:
      - x: 359.05
        y: 288
        ref_to: A5

  - name: Port D4
    type: GROVE
    pins:
      - x: 169.12
        y: 61.01
        ref_to: GND
      - x: 169.12
        y: 72.34
        ref_to: VCC
      - x: 169.12
        y: 83.68
        ref_to: D5
      - x: 169.12
        y: 95.02
        ref_to: D4
  - name: Port A2
    type: GROVE
    pins:
      - x: 169.12
        y: 134.19
        ref_to: GND
      - x: 169.12
        y: 145.53
        ref_to: VCC
      - x: 169.12
        y: 156.87
        ref_to: A3
      - x: 169.12
        y: 168.21
        ref_to: A2
  - name: Port A1
    type: GROVE
    pins:
      - x: 169.12
        y: 207.26
        ref_to: GND
      - x: 169.12
        y: 218.6
        ref_to: VCC
      - x: 169.12
        y: 229.93
        ref_to: A2
      - x: 169.12
        y: 241.27
        ref_to: A1

  - name: Port D3
    type: GROVE
    pins:
      - x: 224.43
        y: 61.01
        ref_to: GND
      - x: 224.43
        y: 72.34
        ref_to: VCC
      - x: 224.43
        y: 83.68
        ref_to: D4
      - x: 224.43
        y: 95.02
        ref_to: D3
  - name: Port D7
    type: GROVE
    pins:
      - x: 224.43
        y: 134.19
        ref_to: GND
      - x: 224.43
        y: 145.53
        ref_to: VCC
      - x: 224.43
        y: 156.87
        ref_to: D8
      - x: 224.43
        y: 168.21
        ref_to: D7
  - name: Port A0
    type: GROVE
    pins:
      - x: 224.43
        y: 207.26
        ref_to: GND
      - x: 224.43
        y: 218.6
        ref_to: VCC
      - x: 224.43
        y: 229.93
        ref_to: A1
      - x: 224.43
        y: 241.27
        ref_to: A0

  - name: Port D2
    type: GROVE
    pins:
      - x: 279.74
        y: 61.01
        ref_to: GND
      - x: 279.74
        y: 72.34
        ref_to: VCC
      - x: 279.74
        y: 83.68
        ref_to: D3
      - x: 279.74
        y: 95.02
        ref_to: D2
  - name: Port D6
    type: GROVE
    pins:
      - x: 279.74
        y: 134.19
        ref_to: GND
      - x: 279.74
        y: 145.53
        ref_to: VCC
      - x: 279.74
        y: 156.87
        ref_to: D7
      - x: 279.74
        y: 168.21
        ref_to: D6
  - name: Port I2C (1)
    type: GROVE
    pins:
      - x: 279.74
        y: 207.26
        ref_to: GND
      - x: 279.74
        y: 218.6
        ref_to: VCC
      - x: 279.74
        y: 229.93
        ref_to: SDA
      - x: 279.74
        y: 241.27
        ref_to: SCL

  - name: Port UART
    type: GROVE
    pins:
      - x: 335.04
        y: 61.01
        ref_to: GND
      - x: 335.04
        y: 72.34
        ref_to: VCC
      - x: 335.04
        y: 83.68
        ref_to: TX
      - x: 335.04
        y: 95.02
        ref_to: RX
  - name: Port D5
    type: GROVE
    pins:
      - x: 335.04
        y: 134.19
        ref_to: GND
      - x: 335.04
        y: 145.53
        ref_to: VCC
      - x: 335.04
        y: 156.87
        ref_to: D6
      - x: 335.04
        y: 168.21
        ref_to: D5
  - name: Port I2C (2)
    type: GROVE
    pins:
      - x: 335.04
        y: 207.26
        ref_to: GND
      - x: 335.04
        y: 218.6
        ref_to: VCC
      - x: 335.04
        y: 229.93
        ref_to: SDA
      - x: 335.04
        y: 241.27
        ref_to: SCL
integrated_devices:
  - name: Built in LED
    pin_template: GENERIC_DIGITAL_ACTUATOR_3v3
    integrated_connection:
      - ref_to: SIG
        host_ref_to: D13
      - ref_to: GND
        host_ref_to: GND
    compatibility:
      - name: LED
        action:
          - name: 'On'
            parameter:
              - name: Brightness
                constraint:
                  min: 0.0
                  max: 100.0
                  unit: PERCENT
          - name: 'Off'
    platforms:
      - platform: ARDUINO_ATSAMD21
        classname: MP_LED_AL
        library_dependency: []
platforms:
- platform: ARDUINO_ATSAMD21
  classname: ''
  library_dependency: []
