id: Blynk-Virtual_Button
brand: Blynk
model: Virtual Button
url: https://docs.blynk.cc/#widgets-controllers-button
type: VIRTUAL
cloud_consume: BLYNK
width: 50
height: 50
property:
- name: virtual pin
  datatype: INTEGER_ENUM
  controltype: DROPDOWN
  value: 0
  constraint:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
compatibility:
- name: Virtual Button
  condition:
  - name: Press
  - name: Press and release
  - name: Not press
platforms:
- platform: ARDUINO_AVR8
  classname: MP_BLYNK_VIRTUAL_BUTTON
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_BLYNK_VIRTUAL_BUTTON
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_BLYNK_VIRTUAL_BUTTON
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_BLYNK_VIRTUAL_BUTTON
  library_dependency: []
