id: KidBright-V1_3
brand: KidBright
model: 32 V1.3
url: https://www.kid-bright.org/
type: CONTROLLER
pio_boardid: esp32dev
width: 510
height: 289
property: []
pin_template: ESP_32
cloud_provide:
- cloud_platform: NETPIE
  classname: MP_NETPIE_ESP
  library_dependency:
  - lamloei/ESP32_Microgear
- cloud_platform: BLYNK
  classname: MP_BLYNK_NODEMCU
  library_dependency:
  - blynkkk/blynk-library
connection_provide:
  - name: '5V (0)'
    type: WIRE
    pins:
      - x: 28
        y: 43
        ref_to: VCC
  - name: '5V (1)'
    type: WIRE
    pins:
      - x: 73
        y: 43
        ref_to: VCC
  - name: 'IN1 (Banana)'
    type: WIRE
    pins:
      - x: 28
        y: 94
        ref_to: '32'
  - name: 'IN2 (Banana)'
    type: WIRE
    pins:
      - x: 73
        y: 94
        ref_to: '33'
  - name: 'IN3 (Banana)'
    type: WIRE
    pins:
      - x: 28
        y: 146
        ref_to: '34'
  - name: 'IN4 (Banana)'
    type: WIRE
    pins:
      - x: 73
        y: 146
        ref_to: '35'
  - name: 'OUT1 (Banana)'
    type: WIRE
    pins:
      - x: 28
        y: 198
        ref_to: '26'
  - name: 'OUT2 (Banana)'
    type: WIRE
    pins:
      - x: 73
        y: 198
        ref_to: '27'
  - name: 'GND (0)'
    type: WIRE
    pins:
      - x: 28
        y: 249
        ref_to: 'GND'
  - name: 'GND (1)'
    type: WIRE
    pins:
      - x: 73
        y: 249
        ref_to: 'GND'
  - name: 'IN1 (Header)'
    type: WIRE
    pins:
      - x: 41.311
        y: 278
        ref_to: '32'
  - name: 'IN2 (Header)'
    type: WIRE
    pins:
      - x: 54.3518
        y: 278
        ref_to: '33'
  - name: 'IN3 (Header)'
    type: WIRE
    pins:
      - x: 67.3927
        y: 278
        ref_to: '34'
  - name: 'IN4 (Header)'
    type: WIRE
    pins:
      - x: 80.4336
        y: 278
        ref_to: '35'
  - name: 'GND (2)'
    type: WIRE
    pins:
      - x: 93.4745
        y: 278
        ref_to: 'GND'
  - name: 'OUT2 (Header)'
    type: WIRE
    pins:
      - x: 106.5154
        y: 278
        ref_to: '27'
  - name: 'OUT1 (Header)'
    type: WIRE
    pins:
      - x: 119.5563
        y: 278
        ref_to: '26'
  - name: 'GND (3)'
    type: WIRE
    pins:
      - x: 119.5563
        y: 264.9932
        ref_to: 'GND'
  - name: '23'
    type: WIRE
    pins:
      - x: 119.5563
        y: 251.9629
        ref_to: '23'
  - name: '19'
    type: WIRE
    pins:
      - x: 119.5563
        y: 238.9327
        ref_to: '19'
  - name: '18'
    type: WIRE
    pins:
      - x: 119.5563
        y: 225.9024
        ref_to: '18'
  - name: 'SDA0'
    type: WIRE
    pins:
      - x: 119.5563
        y: 212.8718
        ref_to: '21'
  - name: 'SCL0'
    type: WIRE
    pins:
      - x: 119.5563
        y: 199.8416
        ref_to: '22'
  - name: '3V3'
    type: WIRE
    pins:
      - x: 119.5563
        y: 186.8113
        ref_to: 'VCC'
  - name: '5V'
    type: WIRE
    pins:
      - x: 119.5563
        y: 173.7811
        ref_to: 'VCC'
        voltage_level: LEVEL_5
  - name: IO0
    type: WIRE
    pins:
      - x: 325.102
        y: 157.7823
        ref_to: '0'
  - name: GND (4)
    type: WIRE
    pins:
      - x: 338.4241
        y: 157.7823
        ref_to: GND
  # KIDBRIGHT [GND, SDA, SCL, 3V3, 5V]
  - name: KB Chain
    type: KB_CHAIN
    pins:
      - x: 447.0278
        y: 77.0844
        ref_to: GND
      - x: 447.0278
        y: 89.894
        ref_to: '4'
      - x: 447.0278
        y: 102.7035
        ref_to: '5'
      - x: 447.0278
        y: 115.5131
        ref_to: VCC
      - x: 447.0278
        y: 128.3226
        ref_to: VCC
        voltage_level: LEVEL_5

integrated_devices:
  - name: Integrated Button (S1)
    platforms:
    - platform: ARDUINO_ESP32
      classname: MP_BUTTON_AL
      library_dependency: []
    pin_template: GENERIC_DIGITAL_SENSOR_3v3
    integrated_connection:
      - ref_to: GND
        host_ref_to: GND
      - ref_to: VCC
        host_ref_to: VCC
      - ref_to: SIG
        host_ref_to: '16'
    compatibility:
    - name: Button
      condition:
      - name: Press
      - name: Press and release
      - name: Not press

  - name: Integrated Button (S2)
    platforms:
    - platform: ARDUINO_ESP32
      classname: MP_BUTTON_AL
      library_dependency: []
    pin_template: GENERIC_DIGITAL_SENSOR_3v3
    integrated_connection:
      - ref_to: GND
        host_ref_to: GND
      - ref_to: VCC
        host_ref_to: VCC
      - ref_to: SIG
        host_ref_to: '14'
    compatibility:
    - name: Button
      condition:
      - name: Press
      - name: Press and release
      - name: Not press

  - name: Integrated Light Sensor
    platforms:
    - platform: ARDUINO_ESP32
      classname: MP_LIGHT_SENSOR_KIDBRIGHT
      library_dependency: []
    pin_template: GENERIC_ANALOG_SENSOR_3v3
    integrated_connection:
      - ref_to: GND
        host_ref_to: GND
      - ref_to: VCC
        host_ref_to: VCC
      - ref_to: SIG
        host_ref_to: '36'
    compatibility:
    - name: Light
      condition:
      - name: Compare
      value:
      - name: Percent
        constraint:
          min: 0
          max: 100
          unit: PERCENT

  - name: Integrated Buzzer
    platforms:
    - platform: ARDUINO_ESP32
      classname: MP_BUZZER
      library_dependency: []
    pin_template: GENERIC_PWM_ACTUATOR_3v3
    integrated_connection:
      - ref_to: GND
        host_ref_to: GND
      - ref_to: VCC
        host_ref_to: VCC
      - ref_to: SIG
        host_ref_to: '13'
    compatibility:
    - name: Buzzer
      action:
      - name: Play Tone
        parameter:
        - name: Tone Frequency
          constraint:
            min: 0
            max: 20000
            unit: HERTZ
        - name: Duration
          constraint:
            min: 0
            max: 1000
            unit: SECOND
      - name: Beep

  - name: Integrated Temperature Sensor
    pin_template: GENERIC_I2C_DEVICE_3v3
    integrated_connection:
      - ref_to: GND
        host_ref_to: GND
      - ref_to: VCC
        host_ref_to: VCC
      - ref_to: SDA
        host_ref_to: '4'
      - ref_to: SCL
        host_ref_to: '5'
    compatibility:
      - name: Temperature
        condition:
          - name: Compare
        value:
          - name: Temperature
            dataType: DOUBLE
            constraint:
              min: -500
              max: 500
              unit: CELSIUS
    platforms:
      - platform: ARDUINO_ESP32
        classname: MP_LM73_I2C1_ESP32
        library_dependency: []

  - name: Integrated RTC
    platforms:
    - platform: ARDUINO_ESP32
      classname: MP_RTC_MCP4971x
      library_dependency:
      - jetstreamc/mcp7941x_arduino_ESP32_I2C1
    pin_template: GENERIC_I2C_DEVICE_3v3
    integrated_connection:
      - ref_to: GND
        host_ref_to: GND
      - ref_to: VCC
        host_ref_to: VCC
      - ref_to: SDA
        host_ref_to: '4'
      - ref_to: SCL
        host_ref_to: '5'
    compatibility:
    - name: RTC
      action:
      - name: Set DateTime
        parameter:
        - name: Date & Time
          constraint: []
      condition:
      - name: Compare
      - name: Check Day
        parameter:
        - name: Day
          constraint:
          - key: Sunday
            value: 1
          - key: Monday
            value: 2
          - key: Tuesday
            value: 3
          - key: Wednesday
            value: 4
          - key: Thursday
            value: 5
          - key: Friday
            value: 6
          - key: Saturday
            value: 7
      value:
      - name: Hour
        constraint: []
      - name: Minute
        constraint: []
      - name: Second
        constraint: []
      - name: Date
        constraint: []
      - name: Month
        constraint: []
      - name: Year
        constraint: []

  - name: Integrated Dot Matrix
    platforms:
    - platform: ARDUINO_ESP32
      classname: MP_8x16MiniMatrix
      library_dependency:
      - adafruit/Adafruit_LED_Backpack-1.1.6
      - adafruit/Adafruit-GFX-Library-1.7.6
    pin_template: GENERIC_I2C_DEVICE_3v3_5
    integrated_connection:
      - ref_to: GND
        host_ref_to: GND
      - ref_to: VCC
        host_ref_to: VCC
      - ref_to: SDA
        host_ref_to: '21'
      - ref_to: SCL
        host_ref_to: '22'
    compatibility:
      - name: Dot Matrix
        action:
          - name: Show Bitmap
            funcname: showBitmap
            parameter:
              - name: Data
          - name: Show Text
            parameter:
              - name: Text
              - name: Size
                value: 1x
                constraint:
                  - key: 1x
                    value: 1
                  - key: 2x
                    value: 2
              - name: Rotation
                value: "0\u00B0"
                constraint:
                  - key: "0\u00B0"
                    value: 0
                  - key: "90\u00B0 CCW"
                    value: 90
                  - key: "180\u00B0 CCW"
                    value: 180
                  - key: "270\u00B0 CCW"
                    value: 270
          - name: Clear
            funcname: clear

platforms:
- platform: ARDUINO_ESP32
  classname: ''
  library_dependency: []
