id: MP-Microphone
brand: Maker Playground
model: Microphone
url: ''
type: MODULE
width: 124
height: 108
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 46
      y: 109
      pin_function: GND
    - x: 57
      y: 109
      pin_function: VCC
    - x: 68
      y: 109
      pin_function: NO_FUNCTION
    - x: 79
      y: 109
      pin_function: ANALOG_OUT
compatibility:
- name: Sound
  condition:
  - name: Compare
  value:
  - name: SoundLevel
    constraint:
      min: 0.0
      max: 100.0
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_MICROPHONE
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_MICROPHONE
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_MICROPHONE
  library_dependency: []
