id: Grove-101020055
brand: SeeedStudio
model: Grove - Gas Sensor(MQ2) - Combustible Gas, Smoke
url: https://www.seeedstudio.com/Grove-Gas-Sensor-MQ2.html
type: MODULE
width: 292
height: 166
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 44
      y: 105.4
      pin_function: GND
    - x: 44
      y: 91.0
      pin_function: VCC
    - x: 44
      y: 76.6
      pin_function: NO_FUNCTION
    - x: 44
      y: 62.2
      pin_function: DIGITAL_OUT
compatibility:
- name: LPG
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_MQ2
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_MQ2
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_MQ2
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_MQ2
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_MQ2
  library_dependency: []
