id: Generic-DC-Fan
brand: Generic
model: Fan DC Motor Module L9110 Fan Module for Arduino
url: https://www.arduinoall.com/product/737/fan-dc-motor-module-l9110-fan-module-for-arduino
type: MODULE
width: 235.329
height: 241.152
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: INA
    type: WIRE
    pins:
    - x: 75.983
      y: 128.556
      pin_function: PWM_IN
  - name: INB
    type: WIRE
    pins:
    - x: 61.67
      y: 128.556
      pin_function: PWM_IN
compatibility:
- name: DC Motor
  action:
  - name: 'On'
    parameter:
    - name: Direction
      value: Forward
      constraint:
      - key: Forward
        value: 1
      - key: Backward
        value: 0
    - name: Speed
      constraint:
        min: 0
        max: 100
        unit: PERCENT
  - name: 'Off'
platforms:
- platform: ARDUINO_AVR8
  classname: MP_L9110
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_L9110
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_L9110
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_L9110
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_L9110
  library_dependency: []
