id: M5Stack-Fire
brand: M5Stack
model: Fire
url: https://docs.m5stack.com/#/en/core/fire
type: CONTROLLER
pio_boardid: m5stack-fire
width: 284
height: 284
pin_template: ESP_32
cloud_provide:
- cloud_platform: NETPIE
  classname: MP_NETPIE_ESP
  library_dependency:
  - lamloei/ESP32_Microgear
- cloud_platform: BLYNK
  classname: MP_BLYNK_NODEMCU
  library_dependency:
  - blynkkk/Blynk-0.6.1
- cloud_platform: BLYNK_BLE
  classname: MP_BLYNK_ESP32_BLE
  library_dependency:
  - blynkkk/Blynk-0.6.1
- cloud_platform: AZURE
  classname: MP_AZURE_ESP
  library_dependency: []
- cloud_platform: REST
  classname: MP_REST_ESP
  library_dependency: []
property: []
connection_provide:
  voltage_level: LEVEL_3v3
  items:
  - name: B
    type: GROVE
    pins:
    - x: 75
      y: 1
      ref_to: GND
    - x: 90
      y: 1
      ref_to: VCC
    - x: 104
      y: 1
      ref_to: '26'
    - x: 118
      y: 1
      ref_to: '36'
  - name: C
    type: GROVE
    pins:
    - x: 183
      y: 1
      ref_to: GND
    - x: 196
      y: 1
      ref_to: VCC
    - x: 211
      y: 1
      ref_to: '17'
    - x: 225
      y: 1
      ref_to: '16'
  - name: A (I2C)
    type: GROVE
    pins:
    - x: 1
      y: 225
      ref_to: GND
    - x: 1
      y: 217
      ref_to: VCC
    - x: 1
      y: 202
      ref_to: '21'
    - x: 1
      y: 188
      ref_to: '22'
integrated_devices:
- name: Integrated TFT LCD
  integrated_connection:
  - host_ref_to: GND
    pin_function: GND
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: '23'
    pin_function: MOSI
  - host_ref_to: '18'
    pin_function: SCK
  compatibility:
  - name: Display
    action:
    - name: Show Text
      parameter:
      - name: Row
        constraint:
          min: 1
          max: 10
          unit: NOT_SPECIFIED
      - name: Text
      - name: Size
        value: 1x
        constraint:
        - key: 1x
          value: 1
        - key: 2x
          value: 2
        - key: 3x
          value: 3
      - name: Align
        value: Left
        constraint:
        - key: Left
          value: 0
        - key: Center
          value: 1
        - key: Right
          value: 2
      - name: Color
        value: White
        constraint:
        - key: Blue
          value: 0
        - key: Cyan
          value: 1
        - key: Dark Cyan
          value: 2
        - key: Dark Green
          value: 3
        - key: Dark Grey
          value: 4
        - key: Green
          value: 5
        - key: Green Yellow
          value: 6
        - key: Light Grey
          value: 7
        - key: Magenta
          value: 8
        - key: Maroon
          value: 9
        - key: Navy
          value: 10
        - key: Olive
          value: 11
        - key: Orange
          value: 12
        - key: Pink
          value: 13
        - key: Purple
          value: 14
        - key: White
          value: 15
        - key: Red
          value: 16
        - key: Yellow
          value: 17
    - name: Clear Row
      parameter:
      - name: Row
        constraint:
          min: 1
          max: 10
          unit: NOT_SPECIFIED
    - name: Clear Screen
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_TFT_M5Stack
    library_dependency:
    - M5Stack/M5Stack-0.2.5
- name: Integrated Buzzer
  integrated_connection:
  - host_ref_to: GND
    pin_function: GND
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: '25'
    pin_function: PWM_IN
  compatibility:
  - name: Buzzer
    action:
    - name: Play Tone
      parameter:
      - name: Tone Frequency
        constraint:
          max: 20000.0
          min: 0.0
          unit: HERTZ
      - name: Duration
        constraint:
          max: 1000.0
          min: 0.0
          unit: SECOND
    - name: Beep
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_BUZZER
    library_dependency: []
- name: Integrated Button A
  integrated_connection:
  - host_ref_to: GND
    pin_function: GND
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: '39'
    pin_function: DIGITAL_OUT
  compatibility:
  - name: Button
    condition:
    - name: Press
    - name: Press and release
    - name: Not press
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_BUTTON_AL
    library_dependency: []
- name: Integrated Button B
  integrated_connection:
  - host_ref_to: GND
    pin_function: GND
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: '38'
    pin_function: DIGITAL_OUT
  compatibility:
  - name: Button
    condition:
    - name: Press
    - name: Press and release
    - name: Not press
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_BUTTON_AL
    library_dependency: []
- name: Integrated Button C
  integrated_connection:
  - host_ref_to: GND
    pin_function: GND
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: '37'
    pin_function: DIGITAL_OUT
  compatibility:
  - name: Button
    condition:
    - name: Press
    - name: Press and release
    - name: Not press
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_BUTTON_AL
    library_dependency: []
- name: Integrated Microphone
  integrated_connection:
  - host_ref_to: GND
    pin_function: GND
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: '34'
    pin_function: ANALOG_OUT
  compatibility:
  - name: Sound
    condition:
    - name: Compare
    value:
    - name: SoundLevel
      constraint:
        min: 0.0
        max: 100.0
        unit: PERCENT
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_MICROPHONE_NORMALIZED
    library_dependency: []
- name: Integrated 9-DOF IMU
  integrated_connection:
  - host_ref_to: GND
    pin_function: GND
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: '21'
    pin_function: SDA
  - host_ref_to: '22'
    pin_function: SCL
  compatibility:
  - name: Accelerometer
    condition:
    - name: Compare
    value:
    - name: Accel_X
      constraint:
        min: -100
        max: 100
        unit: METERPERSECSQUARE
    - name: Accel_Y
      constraint:
        min: -100
        max: 100
        unit: METERPERSECSQUARE
    - name: Accel_Z
      constraint:
        min: -100
        max: 100
        unit: METERPERSECSQUARE
    - name: Accel_Magnitude
      constraint:
        min: 0
        max: 100
        unit: METERPERSECSQUARE
    count: ''
  - name: Gyroscope
    condition:
    - name: Compare
    value:
    - name: Gyro_X
      constraint:
        min: -200
        max: 200
        unit: RADIUSPERSEC
    - name: Gyro_Y
      constraint:
        min: -200
        max: 200
        unit: RADIUSPERSEC
    - name: Gyro_Z
      constraint:
        min: -200
        max: 200
        unit: RADIUSPERSEC
    count: ''
  - name: Magnetometer
    condition:
    - name: Compare
    value:
    - name: Mag_X
      constraint:
        min: -200
        max: 200
        unit: MICROTESLA
    - name: Mag_Y
      constraint:
        min: -200
        max: 200
        unit: MICROTESLA
    - name: Mag_Z
      constraint:
        min: -200
        max: 200
        unit: MICROTESLA
    count: ''
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_MPU9250
    library_dependency:
    - M5Stack/M5Stack-0.2.5
platforms:
- platform: ARDUINO_ESP32
  classname: ''
  library_dependency: []
