id: TowerPro-SG90
brand: Tower Pro
model: SG90 Micro Servo
url: https://www.arduitronics.com/product/283/tower-pro-sg90-mini-micro-servo
type: MODULE
width: 278
height: 184
connection_consume:
  min_voltage: 5
  max_voltage: 5
  items:
  - name: GND
    type: WIRE
    pins:
    - x: 0
      y: 139
      pin_function: GND
  - name: SIG
    type: WIRE
    pins:
    - x: 0
      y: 167
      pin_function: PWM_IN
  - name: VCC
    type: WIRE
    pins:
    - x: 0
      y: 153
      pin_function: VCC
compatibility:
- name: Servo
  action:
  - name: Move To
    parameter:
    - name: Degree
      constraint:
        min: 0
        max: 180
        unit: DEGREE
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SERVO
  library_dependency:
    - arduino-libraries/Servo-1.1.7
- platform: ARDUINO_ESP8266
  classname: MP_SERVO
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_SERVO
  library_dependency:
    - RoboticsBrno/ServoESP32-1.0.3
- platform: ARDUINO_ATSAMD21
  classname: MP_SERVO
  library_dependency:
    - arduino-libraries/Servo-1.1.7
- platform: ARDUINO_ATSAMD51
  classname: MP_SERVO
  library_dependency:
    - adafruit/Servo-adafruit_samd51-2020-12-20
- platform: MICROPYTHON_K210
  classname: MP_SERVO
  library_dependency: []
