id: MP-Buzzer
brand: Maker Playground
model: Buzzer
url: ''
type: MODULE
width: 124
height: 108
property: []
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 79
      y: 110
      pin_function: GND
    - x: 68
      y: 110
      pin_function: VCC
    - x: 57
      y: 110
      pin_function: NO_FUNCTION
    - x: 46
      y: 110
      pin_function: PWM_IN
compatibility:
- name: Buzzer
  action:
  - name: Play Tone
    parameter:
    - name: Tone Frequency
      constraint:
        min: 0
        max: 20000
        unit: HERTZ
    - name: Duration
      constraint:
        min: 0
        max: 1000
        unit: SECOND
  - name: Beep
    parameter: []
  value: []
platforms:
- platform: ARDUINO_AVR8
  classname: MP_BUZZER
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_BUZZER
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_BUZZER
  library_dependency: []
