id: MP-TempHumid
brand: Maker Playground
model: Temperature/Humidity
url: ''
type: MODULE
width: 124
height: 108
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 79
      y: 109
      pin_function: GND
    - x: 68
      y: 109
      pin_function: VCC
    - x: 57
      y: 109
      pin_function: SDA
    - x: 46
      y: 109
      pin_function: SCL
compatibility:
- name: Temperature
  condition:
  - name: Compare
  value:
  - name: Temperature
    constraint:
      min: 0.0
      max: 65.0
      unit: CELSIUS
- name: Humidity
  condition:
  - name: Compare
  value:
  - name: Humidity
    constraint:
      min: 0.0
      max: 100.0
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SHT
  library_dependency:
  - Sensirion/arduino-sht
- platform: ARDUINO_ESP8266
  classname: MP_SHT
  library_dependency:
  - Sensirion/arduino-sht
- platform: ARDUINO_ESP32
  classname: MP_SHT
  library_dependency:
  - Sensirion/arduino-sht
