id: KMM-depa-Ag-1
brand: KMM
model: depa Ag 1.0
url: ''
type: CONTROLLER
pio_boardid: esp32dev
cloud_provide:
- cloud_platform: NETPIE
  classname: MP_NETPIE_ESP
  library_dependency:
  - lamloei/ESP32_Microgear
- cloud_platform: BLYNK
  classname: MP_BLYNK_NODEMCU
  library_dependency:
  - blynkkk/Blynk-0.6.1
- cloud_platform: BLYNK_BLE
  classname: MP_BLYNK_ESP32_BLE
  library_dependency:
  - blynkkk/Blynk-0.6.1
- cloud_platform: AZURE
  classname: MP_AZURE_ESP
  library_dependency: []
- cloud_platform: REST
  classname: MP_REST_ESP
  library_dependency: []
width: 578.0
height: 471.0
property: []
pin_template: ESP_32
connection_provide:
  voltage_level: LEVEL_3v3
  items:
  - name: B(-)
    type: WIRE
    pins:
    - x: 55
      y: 470
      ref_to: '3'
      function: RS485_Negative
      voltage_level: LEVEL_12
  - name: A(+)
    type: WIRE
    pins:
    - x: 84
      y: 470
      ref_to: '1'
      function: RS485_Positive
      voltage_level: LEVEL_12
  - name: GND
    type: WIRE
    pins:
    - x: 227
      y: 470
      ref_to: GND
      voltage_level: LEVEL_12
  - name: VCC
    type: WIRE
    pins:
    - x: 255
      y: 470
      ref_to: VCC
      voltage_level: LEVEL_12
  - name: TX
    type: WIRE
    pins:
    - x: 206
      y: 0
      ref_to: '1'
  - name: RX
    type: WIRE
    pins:
    - x: 226
      y: 0
      ref_to: '3'
  - name: D14
    type: WIRE
    pins:
    - x: 246
      y: 0
      ref_to: '14'
  - name: D13
    type: WIRE
    pins:
    - x: 266
      y: 0
      ref_to: '13'
  - name: D12
    type: WIRE
    pins:
    - x: 286
      y: 0
      ref_to: '12'
  - name: 3.3V
    type: WIRE
    pins:
    - x: 306
      y: 0
      ref_to: VCC
  - name: 5V
    type: WIRE
    pins:
    - x: 326
      y: 0
      ref_to: VCC
      voltage_level: LEVEL_5
  - name: GND0
    type: WIRE
    pins:
    - x: 346
      y: 0
      ref_to: GND
compatibility: []
platforms:
- platform: ARDUINO_ESP32
  classname: ''
  library_dependency: []
integrated_devices:
- name: Integrated OLED
  integrated_connection:
  - host_ref_to: '22'
    pin_function: SCL
  - host_ref_to: '21'
    pin_function: SDA
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: Display
    action:
    - name: Show Text
      parameter:
      - name: Row
        constraint:
          min: 1
          max: 10
          unit: NOT_SPECIFIED
      - name: Text
      - name: Size
        value: 1x
        constraint:
        - key: 1x
          value: 1
        - key: 2x
          value: 2
        - key: 3x
          value: 3
      - name: Align
        value: Left
        constraint:
        - key: Left
          value: 0
        - key: Center
          value: 1
        - key: Right
          value: 2
      - name: Color
        value: White
        constraint:
        - key: Blue
          value: 0
        - key: Cyan
          value: 1
        - key: Dark Cyan
          value: 2
        - key: Dark Green
          value: 3
        - key: Dark Grey
          value: 4
        - key: Green
          value: 5
        - key: Green Yellow
          value: 6
        - key: Light Grey
          value: 7
        - key: Magenta
          value: 8
        - key: Maroon
          value: 9
        - key: Navy
          value: 10
        - key: Olive
          value: 11
        - key: Orange
          value: 12
        - key: Pink
          value: 13
        - key: Purple
          value: 14
        - key: White
          value: 15
        - key: Red
          value: 16
        - key: Yellow
          value: 17
    - name: Clear Row
      parameter:
      - name: Row
        constraint:
          min: 1
          max: 10
          unit: NOT_SPECIFIED
    - name: Clear Screen
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_OLED_SSD1306_128x64
    library_dependency:
    - adafruit/Adafruit_SSD1306-1.2.9
    - adafruit/Adafruit-GFX-Library-1.5.2
- name: Integrated Button (SW1)
  integrated_connection:
  - host_ref_to: '34'
    pin_function: DIGITAL_OUT
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: Button
    condition:
    - name: Press and release
    - name: Press
    - name: Not press
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_BUTTON_AL
    library_dependency: []
- name: Integrated Button (SW2)
  integrated_connection:
  - host_ref_to: '35'
    pin_function: DIGITAL_OUT
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: Button
    condition:
    - name: Press and release
    - name: Press
    - name: Not press
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_BUTTON_AL
    library_dependency: []
- name: Integrated Button (SW3)
  integrated_connection:
  - host_ref_to: '32'
    pin_function: DIGITAL_OUT
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: Button
    condition:
    - name: Press and release
    - name: Press
    - name: Not press
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_BUTTON_AL
    library_dependency: []
- name: Integrated Relay (R1)
  integrated_connection:
  - host_ref_to: '17'
    pin_function: DIGITAL_IN
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: Relay Module
    action:
    - name: 'On'
    - name: 'Off'
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_RELAY_AL
    library_dependency: []
- name: Integrated Relay (R2)
  integrated_connection:
  - host_ref_to: '16'
    pin_function: DIGITAL_IN
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: Relay Module
    action:
    - name: 'On'
    - name: 'Off'
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_RELAY_AL
    library_dependency: []
- name: Integrated Relay (R3)
  integrated_connection:
  - host_ref_to: '4'
    pin_function: DIGITAL_IN
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: Relay Module
    action:
    - name: 'On'
    - name: 'Off'
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_RELAY_AL
    library_dependency: []
- name: Integrated LED (LED on ESP32)
  integrated_connection:
  - host_ref_to: '2'
    pin_function: DIGITAL_IN
  - host_ref_to: VCC
    pin_function: VCC
  - host_ref_to: GND
    pin_function: GND
  compatibility:
  - name: LED
    action:
    - name: 'On'
      parameter:
      - name: Brightness
        value: 100.0
        constraint:
          min: 0.0
          max: 100.0
          unit: PERCENT
    - name: 'Off'
  platforms:
  - platform: ARDUINO_ESP32
    classname: MP_LED_AH
    library_dependency: []
