id: SeeedStudio-104030003
brand: SeeedStudio
model: Grove - 4-Digit Display
url: https://www.seeedstudio.com/Grove-4-Digit-Display.html
type: MODULE
width: 180
height: 103
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
      - x: 180
        y: 36
        pin_function:
          - GND
      - x: 180
        y: 47
        pin_function:
          - VCC
      - x: 180
        y: 58
        pin_function:
          - DIGITAL_OUT
          - DIGITAL_IN
      - x: 180
        y: 69
        pin_function:
          - DIGITAL_OUT
          - DIGITAL_IN
compatibility:
- name: 7 Segment
  action:
  - name: Show Number
    parameter:
    - name: Number
      constraint:
        min: -999
        max: 9999
        unit: NOT_SPECIFIED
  - name: Show Two Numbers with Colon
    parameter:
    - name: Before colon
      constraint:
        min: -9
        max: 99
        unit: NOT_SPECIFIED
    - name: After colon
      constraint:
        min: -9
        max: 99
        unit: NOT_SPECIFIED
  - name: 'Off'
platforms:
- platform: ARDUINO_AVR8
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ESP32
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ESP8266
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ATSAMD21
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
- platform: ARDUINO_ATSAMD51
  classname: MP_TM1637_DISPLAY
  library_dependency:
  - avishorp/TM1637
