id: INEX-8000266
brand: INEX
model: ZX-LED
url: https://inex.co.th/shop/zx-led-clear.html
type: MODULE
width: 94.0
height: 188.0
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: INEX3
    pins:
    - x: 56
      y: 175
      pin_function: GND
    - x: 48
      y: 175
      pin_function: PWM_IN
    - x: 40
      y: 175
      pin_function: VCC
compatibility:
- name: LED
  action:
  - name: 'On'
    parameter:
    - name: Brightness
      constraint:
        min: 0.0
        max: 100.0
        unit: PERCENT
  - name: 'Off'
platforms:
- platform: ARDUINO_AVR8
  classname: MP_LED_AH
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_LED_AH
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_LED_AH
  library_dependency: []
- platform: RASPBERRYPI
  classname: MP_PWM_LED_AH
  library_dependency: []
