id: SeeedStudio-316010005
brand: SeeedStudio
model: Grove - Servo Motor
url: https://www.seeedstudio.com/Grove-Servo-p-1241.html
type: MODULE
width: 278
height: 184
connection_consume:
  min_voltage: 5
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 0
      y: 139
      pin_function: GND
    - x: 0
      y: 153
      pin_function: VCC
    - x: 0
      y: 153
      pin_function: NO_FUNCTION
    - x: 0
      y: 167
      pin_function: PWM_IN
compatibility:
- name: Servo
  action:
  - name: Move To
    parameter:
    - name: Degree
      constraint:
        min: 0
        max: 180
        unit: DEGREE
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SERVO
  library_dependency:
    - arduino-libraries/Servo-1.1.7
- platform: ARDUINO_ESP8266
  classname: MP_SERVO
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_SERVO
  library_dependency:
    - RoboticsBrno/ServoESP32-1.0.3
- platform: ARDUINO_ATSAMD21
  classname: MP_SERVO
  library_dependency:
    - arduino-libraries/Servo-1.1.7
- platform: ARDUINO_ATSAMD51
  classname: MP_SERVO
  library_dependency:
    - adafruit/Servo-adafruit_samd51-2020-12-20
- platform: MICROPYTHON_K210
  classname: MP_SERVO
  library_dependency: []