id: Adafruit-1063
brand: Adafruit
model: Electret Microphone Amplifier - MAX4466 with Adjustable Gain
url: https://www.adafruit.com/product/1063
type: MODULE
width: 80.0
height: 123.0
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: OUT
    type: WIRE
    pins:
    - x: 21.646
      y: 110.924
      pin_function: ANALOG_OUT
  - name: GND
    type: WIRE
    pins:
    - x: 36.046
      y: 110.924
      pin_function: GND
  - name: VCC
    type: WIRE
    pins:
    - x: 50.446
      y: 110.924
      pin_function: VCC
compatibility:
- name: Sound
  condition:
  - name: Compare
  value:
  - name: SoundLevel
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_MICROPHONE
  library_dependency: []
