id: Grove-101020555
brand: SeeedStudio
model: Grove - 1-Wire Thermocouple Amplifier (MAX31850K)
url: https://www.seeedstudio.com/Grove-1-Wire-Thermocouple-Amplifier-MAX31850K.html
type: MODULE
width: 303
height: 171
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 13
      y: 64
      pin_function: GND
    - x: 13
      y: 78.4
      pin_function: VCC
    - x: 13
      y: 92.8
      pin_function: NO_FUNCTION
    - x: 13
      y: 107.2
      pin_function: DIGITAL_OUT
compatibility:
- name: Temperature
  condition:
  - name: Compare
  value:
  - name: Temperature
    constraint:
      min: -50.0
      max: 600.0
      unit: CELSIUS
platforms:
- platform: ARDUINO_AVR8
  classname: MP_MAX31850K
  library_dependency:
  - SeeedStudio/Seeed_MAX31850K-master
  - milesburton/Arduino-Temperature-Control-Library-3.8.0
  - PaulStoffregen/OneWire-2.3.4
- platform: ARDUINO_ESP8266
  classname: MP_MAX31850K
  library_dependency:
  - SeeedStudio/Seeed_MAX31850K-master
  - milesburton/Arduino-Temperature-Control-Library-3.8.0
  - PaulStoffregen/OneWire-2.3.4
- platform: ARDUINO_ESP32
  classname: MP_MAX31850K
  library_dependency:
  - SeeedStudio/Seeed_MAX31850K-master
  - milesburton/Arduino-Temperature-Control-Library-3.8.0
  - PaulStoffregen/OneWire-2.3.4
- platform: ARDUINO_ATSAMD21
  classname: MP_MAX31850K
  library_dependency:
  - SeeedStudio/Seeed_MAX31850K-master
  - milesburton/Arduino-Temperature-Control-Library-3.8.0
  - PaulStoffregen/OneWire-2.3.4
- platform: ARDUINO_ATSAMD51
  classname: MP_MAX31850K
  library_dependency:
  - SeeedStudio/Seeed_MAX31850K-master
  - milesburton/Arduino-Temperature-Control-Library-3.8.0
  - PaulStoffregen/OneWire-2.3.4
