id: MP-Distance-V1
brand: Maker Playground
model: Distance v1.0
url: ''
type: MODULE
width: 171
height: 114
property:
- name: Mode
  datatype: STRING_INT_ENUM
  optional: true
  controltype: DROPDOWN
  value: High Accuracy
  constraint:
  - key: High Accuracy
    value: 0
  - key: High Speed
    value: 1
- name: Use Long Range
  datatype: STRING_INT_ENUM
  optional: true
  controltype: DROPDOWN
  value: 'Yes'
  constraint:
  - key: 'Yes'
    value: 1
  - key: 'No'
    value: 0
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 69
      y: 0
      pin_function: GND
    - x: 80
      y: 0
      pin_function: VCC
    - x: 91
      y: 0
      pin_function: SDA
    - x: 102
      y: 0
      pin_function: SCL
compatibility:
- name: Distance
  condition:
  - name: Compare
    parameter: []
  value:
  - name: Distance
    constraint:
      min: 0.3
      max: 120
      unit: CENTIMETER
platforms:
- platform: ARDUINO_AVR8
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
- platform: ARDUINO_ESP8266
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
- platform: ARDUINO_ESP32
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
- platform: ARDUINO_ATSAMD51
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
