id: Generic-RGBLED-Module-CC
brand: Generic
model: RGB LED Module Common Cathode
url: https://www.arduinoall.com/product/332/rgb-3-color-full-color-ky-016-led-module-for-arduino-avr-pic
type: MODULE
width: 86
height: 107
need_breadboard: true
breadboard_placement: ONE_SIDE
connection_consume:
  min_voltage: 5
  max_voltage: 5
  items:
  - name: R
    type: WIRE
    pins:
    - x: 20.743
      y: 90.968
      pin_function: PWM_IN
  - name: G
    type: WIRE
    pins:
    - x: 35.144
      y: 90.968
      pin_function: PWM_IN
  - name: B
    type: WIRE
    pins:
    - x: 49.544
      y: 90.968
      pin_function: PWM_IN
  - name: '-'
    type: WIRE
    pins:
    - x: 63.944
      y: 90.968
      pin_function: GND
compatibility:
- name: RGB LED
  action:
  - name: 'On'
    parameter:
    - name: Red
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Green
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Blue
      constraint:
        min: 0
        max: 255
        unit: NOT_SPECIFIED
    - name: Brightness
      constraint:
        min: 0
        max: 100
        unit: NOT_SPECIFIED
  - name: 'Off'
platforms:
- platform: ARDUINO_AVR8
  classname: MP_RGB_LED_CC
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_RGB_LED_CC
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_RGB_LED_CC
  library_dependency: []
