id: Grove-101020017
brand: SeeedStudio
model: Grove Rotary Angle Sensor
url: https://www.seeedstudio.com/Grove-Rotary-Angle-Sensor-p-770.html
type: MODULE
width: 132
height: 114
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: GROVE
    pins:
    - x: 48.99
      y: 94.71
      pin_function: GND
    - x: 60.33
      y: 94.71
      pin_function: VCC
    - x: 71.66
      y: 94.71
      pin_function: NO_FUNCTION
    - x: 83
      y: 94.71
      pin_function: ANALOG_OUT
compatibility:
- name: POT
  condition:
  - name: Compare
    parameter: []
  value:
  - name: Percent
    constraint:
      min: 0.0
      max: 100.0
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ESP8266
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ESP32
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ATSAMD21
  classname: MP_TRIMPOT
  library_dependency: []
- platform: ARDUINO_ATSAMD51
  classname: MP_TRIMPOT
  library_dependency: []
