id: INEX-ZX-LUX
brand: INEX
model: ZX-LUX
url: https://inex.co.th/shop/zx-lux.html
type: MODULE
width: 136.0
height: 250.0
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: I2C
    type: GROVE
    pins:
    - x: 85.01
      y: 11.4
      pin_function: GND
    - x: 73.67
      y: 11.4
      pin_function: VCC
    - x: 62.33
      y: 11.4
      pin_function: SDA
    - x: 50.99
      y: 11.4
      pin_function: SCL
compatibility:
- name: Light
  condition:
  - name: Compare
  value:
  - name: Percent
    constraint:
      min: 0
      max: 100
      unit: PERCENT
  - name: Intensity
    constraint:
      min: 0
      max: 65535
      unit: LUX
platforms:
- platform: ARDUINO_AVR8
  classname: MP_BH1750
  library_dependency:
  - claws/BH1750
- platform: ARDUINO_ESP8266
  classname: MP_BH1750
  library_dependency:
  - claws/BH1750
- platform: ARDUINO_ESP32
  classname: MP_BH1750
  library_dependency:
  - claws/BH1750
