id: MP-TempHumid-V1
brand: Maker Playground
model: Temperature/Humidity v1
url: ''
type: MODULE
width: 171
height: 114
property: []
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: Port
    type: MAKER_PLAYGROUND
    pins:
    - x: 69
      y: 0
      pin_function: GND
    - x: 80
      y: 0
      pin_function: VCC
    - x: 91
      y: 0
      pin_function: SDA
    - x: 102
      y: 0
      pin_function: SCL
compatibility:
- name: Temperature
  condition:
  - name: Compare
  value:
  - name: Temperature
    constraint:
      min: -500
      max: 500
      unit: CELSIUS
- name: Humidity
  condition:
  - name: Compare
  value:
  - name: Humidity
    constraint:
      min: 0
      max: 100
      unit: PERCENT
platforms:
- platform: ARDUINO_AVR8
  classname: MP_SHT
  library_dependency:
  - Sensirion/arduino-sht
- platform: ARDUINO_ESP8266
  classname: MP_SHT
  library_dependency:
  - Sensirion/arduino-sht
- platform: ARDUINO_ESP32
  classname: MP_SHT
  library_dependency:
  - Sensirion/arduino-sht
