id: Generic-VL53L0X
brand: Generic
model: Laser Ranging Distance Sensor
url: "https://www.arduinoall.com/product/1584/vl53l0x-v2-laser-ranging-distance-sensor-\u0E40\
  \u0E0B\u0E19\u0E40\u0E0B\u0E2D\u0E23\u0E4C\u0E27\u0E31\u0E14\u0E23\u0E30\u0E22\u0E30\
  \u0E17\u0E32\u0E07\u0E14\u0E49\u0E27\u0E22\u0E41\u0E2A\u0E07\u0E40\u0E25\u0E40\u0E0B\
  \u0E2D\u0E23\u0E4C-0-3-120-\u0E40\u0E0B\u0E19\u0E15\u0E34\u0E40\u0E21\u0E15\u0E23"
type: MODULE
width: 128
height: 98
property:
- name: Mode
  datatype: STRING_INT_ENUM
  optional: true
  controltype: DROPDOWN
  value: High Accuracy
  constraint:
  - key: High Accuracy
    value: 0
  - key: High Speed
    value: 1
- name: Use Long Range
  datatype: STRING_INT_ENUM
  optional: true
  controltype: DROPDOWN
  value: 'Yes'
  constraint:
  - key: 'Yes'
    value: 1
  - key: 'No'
    value: 0
connection_consume:
  min_voltage: 3.3
  max_voltage: 5
  items:
  - name: VCC
    type: WIRE
    pins:
    - x: 34.054
      y: 98
      pin_function: VCC
  - name: GND
    type: WIRE
    pins:
    - x: 45.798
      y: 98
      pin_function: GND
  - name: SCL
    type: WIRE
    pins:
    - x: 57.542
      y: 98
      pin_function: SCL
  - name: SDA
    type: WIRE
    pins:
    - x: 69.286
      y: 98
      pin_function: SDA
compatibility:
- name: Distance
  condition:
  - name: Compare
  value:
  - name: Distance
    constraint:
      min: 0.3
      max: 120
      unit: CENTIMETER
platforms:
- platform: ARDUINO_AVR8
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
- platform: ARDUINO_ESP8266
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
- platform: ARDUINO_ESP32
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
- platform: ARDUINO_ATSAMD51
  classname: MP_VL53L0X
  library_dependency:
  - pololu/vl53l0x-arduino-1.3.0
