name: Build and Deploy MakerPlayground Library

on:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build the library
      run: |
        python build.py
    - name: Deploy <ver>.zip to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
          source_dir: './'
          container_name: 'release'
          connection_string: ${{ secrets.AZURESTORAGECONNECTIONSTRING }}
          extra_args: '--pattern *.zip --destination-path library --overwrite'
    - name: Deploy version.json to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
          source_dir: './'
          container_name: '$web'
          connection_string: ${{ secrets.AZURESTORAGECONNECTIONSTRING }}
          extra_args: '--pattern version.json --content-type application/json --destination-path library --overwrite'
    - name: Deploy device_list.json to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
          source_dir: './'
          container_name: '$web'
          connection_string: ${{ secrets.AZURESTORAGECONNECTIONSTRING }}
          extra_args: '--pattern device_list.json --content-type application/json --destination-path library --overwrite'
