name: Build and Deploy MakerPlayground Library

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build the library
      run: |
        python build.py
    - name: Get the version number
      id: get-version-string
      run: |
        echo "VERSION_STRING=$(ls *.zip | sed -e 's/\.zip$//')" >> "$GITHUB_OUTPUT"
    - name: Push tag
      id: push-commit-tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.get-version-string.outputs.VERSION_STRING }}
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ steps.push-commit-tag.outputs.new_tag }}
          body: ${{ github.event.head_commit.message }}
          fail_on_unmatched_files: true
          files: |
            *.zip
            version.json
            device_list.json